### ISSUE TITLE
你好,前端框架是还没有搭建好吗?

### ISSUE THREAD

**Issue by jucheap** [anjoy8/Blog.Core#1]
你好,前端框架是还没有搭建好吗?我在代码库里面没有看到前端项目的代码

**Comment by anjoy8** [comment]
你好，
vue 前端的已经写了，只不过是简单的 
https://github.com/anjoy8/Blog.Vue
只有首页和详情页，你可以配合着我的博客看看
https://www.cnblogs.com/laozhang-is-phi/p/9640974.html

**Comment by anjoy8** [comment]
部署地址：
http://vue.blog.azlinli.com

**Comment by jucheap** [comment]
> 你好，
> vue 前端的已经写了，只不过是简单的
> https://github.com/anjoy8/Blog.Vue
> 只有首页和详情页，你可以配合着我的博客看看
> https://www.cnblogs.com/laozhang-is-phi/p/9640974.html

好的，我也刚刚看到，谢谢!
