### ISSUE TITLE
项目无sqlsugar的日志功能

### ISSUE THREAD

**Issue by 813026685** [anjoy8/Blog.Core#10]
希望增加sqlsugar的日志功能

**Comment by anjoy8** [comment]
1、我在仓储层，本来是写了一个自定义的日志记录，没有用Log4，只是一个简单的日志输出；
2、刚刚试了试，我把LogHelper，移动到了 Common 层，但是在 Repository 层的 DbContext.cs 中依旧不能使用构造函数注入；
3、因为 DbContext 这个实体类并没有自己的接口，而且API层也解耦了 Repository 层，所以，我是这么用的，
![image](https://user-images.githubusercontent.com/28941816/56265437-2341bc80-611c-11e9-830d-f831a234872f.png)

4、如果你想在 BaseRepository 中注入的话，就需要在每一个子类仓储中都注入，改动太大

**Comment by anjoy8** [comment]
![image](https://user-images.githubusercontent.com/28941816/56265551-6ef46600-611c-11e9-9be4-ec095760ce38.png)
![image](https://user-images.githubusercontent.com/28941816/56265563-7a479180-611c-11e9-8a45-08daa0f7a283.png)

我还没想到那种，只需要在父类构造函数注入，而不用管子类的

**Comment by 813026685** [comment]
那就要考虑日志这块不能用注入了
