### ISSUE TITLE
aop切面日志,异步方法出错之后记录日志之后会跳到全局异常处理再记录异常一次

### ISSUE THREAD

**Issue by huguodong** [anjoy8/Blog.Core#100]
LogEx方法执行完之后会跳转到全局异常GlobalExceptionsFilter再记录一次，不知道是否是正常现象，目前我是取消了Aop的异常日志记录改由全局异常去记录。

**Comment by anjoy8** [comment]
测试，未发现问题，打断点试试吧

![ddd](https://user-images.githubusercontent.com/28941816/89885381-8dc61800-dbfd-11ea-8460-abb02a45f5db.gif)
