### ISSUE TITLE
小白提问 如何自定义一个调试用的万能jwt?

### ISSUE THREAD

**Issue by JustMySpace** [anjoy8/Blog.Core#102]
希望能设置一个jwt 用作登录指定账户 从而跳过登录步骤,方便调试.
在代码里找了一圈 看着像的地方都不会进断点...

**Comment by anjoy8** [comment]
1、注释掉  [Authorize(Permissions.Name)] ，取消加权；
2、设置一个token，过期时间为一年（AuthorizationSetup.cs 设置 expiration: TimeSpan.FromSeconds(60 * 60)）；
3、在权限处理器 PermissionHandler.cs 中，配置：

```
protected override async Task HandleRequirementAsync(AuthorizationHandlerContext context, PermissionRequirement requirement)
{


#if DEBUG
            context.Succeed(requirement);
            return;
#endif
```

**Comment by JustMySpace** [comment]
感谢~
