### ISSUE TITLE
接口权限BUG

### ISSUE THREAD

**Issue by blue20171027** [anjoy8/Blog.Core#103]
**业务bug**
修改菜单管理中的api接口的时候，RoleModulePermission这张关系表没改，这会导致权限验证有问题。

举个例子：假设我用户管理查询这里的接口配置错误，配成了/api/role/get这个，然后我在权限分配那把菜单权限也给了，这个时候我再去菜单管理中把接口换成/api/user/get， 关系表中对应的id还是/api/role/get这个接口的，我这时去请求/api/user/get就提示没权限。

**Comment by anjoy8** [comment]
http://118.25.251.113:7077/
麻烦你这里演示一下吧，我没看懂

**Comment by blue20171027** [comment]
![image](https://user-images.githubusercontent.com/33139361/90302248-75911a00-ded7-11ea-847d-3b87c1d7ce36.png)
![image](https://user-images.githubusercontent.com/33139361/90302257-85a8f980-ded7-11ea-9047-1627bb6728c7.png)
也就是数据不一致
