### ISSUE TITLE
postgresql 数据库，联合查询是否有问题？

### ISSUE THREAD

**Issue by kxf3199** [anjoy8/Blog.Core#106]
我使用mysql库前后端都没问题，改成postgreSql后一直提示登录失败无权限，跟踪代码发现在这个函数（public async Task<List<RoleModulePermission>> RoleModuleMaps()）里，联合查询role  modules都是null，按aop中的查询sql语句直接进库查是没问题的，请问这里是什么问题，是否解决一下？

**Comment by anjoy8** [comment]
抱歉，我没有PostgreSql数据库，无法测试。
你可以自行调试，当然你如果愿意，可以给我开一个远程db连接账号，我可以测试。

肯定是可以运行的，有其他人使用过。

**Comment by kxf3199** [comment]
肯定是有问题的，我自己下载sqlsugar源码跟踪调试找到了问题，在sqlsugar项目中PostgreSQLQueryBuilder.cs文件里
对于复杂模型，也就是多表联合查询，带有AS  .的sql语句判断的正则表达式原始如下
 **public override bool IsComplexModel(string sql)
        {
            return Regex.IsMatch(sql, @"AS \w+\.\w+");
        }**
多表联合的语句如下：
SELECT  "r"."isdeleted" AS "role.isdeleted" , "r"."name" AS "role.name" , "r"."description" AS "role.description" , "r"."ordersort" AS "role.ordersort" , "r"."enabled" AS "role.enabled" , "r"."createid" AS "role.createid" , "r"."createby" AS "role.createby" , "r"."createtime" AS "role.createtime" , "r"."modifyid" AS "role.modifyid" , "r"."modifyby" AS "role.modifyby" , "r"."modifytime" AS "role.modifytime" , "r"."id" AS "role.id" , "m"."isdeleted" AS "modules.isdeleted" , "m"."parentid" AS "modules.parentid" , "m"."name" AS "modules.name" , "m"."linkurl" AS "modules.linkurl" , "m"."area" AS "modules.area" , "m"."controller" AS "modules.controller" , "m"."action" AS "modules.action" , "m"."icon" AS "modules.icon" , "m"."code" AS "modules.code" , "m"."ordersort" AS "modules.ordersort" , "m"."description" AS "modules.description" , "m"."ismenu" AS "modules.ismenu" , "m"."enabled" AS "modules.enabled" , "m"."createid" AS "modules.createid" , "m"."createby" AS "modules.createby" , "m"."createtime" AS "modules.createtime" , "m"."modifyid" AS "modules.modifyid" , "m"."modifyby" AS "modules.modifyby" , "m"."modifytime" AS "modules.modifytime" , "m"."id" AS "modules.id" , "rmp"."isdeleted" AS "isdeleted"  FROM "rolemodulepermission" rmp Left JOIN "modules" m ON ( "rmp"."moduleid" = "m"."id" )  Left JOIN "role" r ON ( "rmp"."roleid" = "r"."id" )   WHERE ((( "rmp"."isdeleted" = @IsDeleted0 ) AND ( "m"."isdeleted" = @IsDeleted1 )) AND ( "r"."isdeleted" = @IsDeleted2 )) 
 **AS "role.i**  作者意思应该是匹配AS  加上. ，漏掉了双引号，匹配不上，然后后面就按通常模型去构建数据了，造成上面我说的那个问题，我把正则表达式改成下面这样
**public override bool IsComplexModel(string sql)
        {
            return Regex.IsMatch(sql, @"AS\s""\w+\.\w+");
        }**
程序就通了，可以登录上了

**Comment by anjoy8** [comment]
ok,也就是说是sqlsugar源码问题？
我和作者说下，当然你也可以给他提个issue。

**Comment by kxf3199** [comment]
对，你可以验证一下，postgresql安装也不困难，我在他那里提了issue了，不过我找到问题后又关闭了issue,我把源码正则表达式改了后，你的blog.core就可以正常用了，不过你的model层里，列类型可不可以不用nvarchar？改成varchar就通用了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "anjoy8/Blog.Core"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 下午5:49
收件人:&nbsp;"anjoy8/Blog.Core"<Blog.Core@noreply.github.com&gt;;
抄送:&nbsp;"kxf3199"<kxf3199@163.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [anjoy8/Blog.Core] postgresql 数据库，联合查询是否有问题？ (#106)





 
ok,也就是说是sqlsugar源码问题？
 我和作者说下，当然你也可以给他提个issue。

**Comment by anjoy8** [comment]
ok
postgreSql问题，我已经和作者sync了，等他有时间会处理下，**到时候我会在这里给你回复**。

关于model的columnType，我用nvarchar是为了**sqlserver的汉字乱码**问题，当然改varchar也可以的。

**Comment by anjoy8** [comment]
你这个是什么版本的pgsql？

**Comment by kxf3199** [comment]
11.5

**Comment by anjoy8** [comment]
问题已被SqlSugar官方解决。升级最新5.0.0.17，
可测试
