### ISSUE TITLE
数据库使用Oracle，怎么运行起来呢？

### ISSUE THREAD

**Issue by xiaosa1944** [anjoy8/Blog.Core#108]
作者，你好！本项目使用oracle数据库怎么运行起来呢？运行的时候创建数据库会出错，把创建数据库的代码注释后，创建表也会出错！

**Comment by anjoy8** [comment]
配置数据库连接字符串就行，
报错就看报错信息，
或者手动创建一个空的数据库，然后再创建表，
如果还有错误，根据错误调整，

下次提问题，把错误粘贴出来。

**Comment by xiaosa1944** [comment]
数据库配置都没有问题，已经创建了一个空的数据库，出现如下错误：
![image](https://user-images.githubusercontent.com/8485380/91018161-cfa18600-e621-11ea-9884-a5232ffca584.png)

**Comment by anjoy8** [comment]
看具体的堆栈信息

**Comment by TaoDuanz** [comment]
我也出现这个错误，请问怎么解决，已经手动创建数据库

      "ConnId": "WMBLOG_ORACLE",
      "DBType": 3,
      "Enabled": true,
      "HitRate": 10,
      "Connection": "Data Source=localhost/orcl;User ID=system;Password=ntidba"
