### ISSUE TITLE
jwt token 失效问题

### ISSUE THREAD

**Issue by liuyangyi** [anjoy8/Blog.Core#109]
目前在  
        var permissionRequirement = new PermissionRequirement(
                "/api/denied",// 拒绝授权的跳转地址（目前无用）
                permission,
                ClaimTypes.Role,//基于角色的授权
                Issuer,//发行人
                Audience,//听众
                signingCredentials,//签名凭据
                expiration: TimeSpan.FromHours(24)//接口的过期时间
                );

小程序在使用的时候，这个地方已经修改过   TimeSpan.FromSeconds(60 * 60 * 2) 对应过期时间，但是还是会有几率 很快过期

请问是需要添加 刷新token 过期时间的接口吗

**Comment by anjoy8** [comment]
打断点调试，
token不能被刷新，
做日志记录
