### ISSUE TITLE
appsettings.json操作类 建议

### ISSUE THREAD

**Issue by 813026685** [anjoy8/Blog.Core#11]
static Appsettings()
        {
            string Path = "appsettings.json";
            if (Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Development")
            {
                Path = "appsettings.Development.json";
            }

            Configuration = new ConfigurationBuilder()
            .Add(new JsonConfigurationSource { Path = Path, ReloadOnChange = true })//请注意要把当前appsetting.json 文件->右键->属性->复制到输出目录->始终复制
            .Build();
        }
增加环境变量的判断

**Comment by anjoy8** [comment]
感谢，我一会儿加上！

**Comment by 813026685** [comment]
要是有精力的话 建议把日志功能扩展起来 性能监控 行为监控 sql执行情况等作为系统基础功能 单独讲一下

**Comment by 813026685** [comment]
这么写实际上有个问题
比如sql连接字符串配置在appsettings.json 在配置了 而在appsettings.Development.json没有配置，
在程序运行时就查不到数据，但是不会抛错！

**Comment by anjoy8** [comment]
没看到你上边的问题，你好像已经解决了，我就不说了，
-------------
我刚更新了下，这样，就可以不用清理解决方案了，
![image](https://user-images.githubusercontent.com/28941816/56792324-ee301b00-683b-11e9-8f8b-57104c6bc421.png)
