### ISSUE TITLE
事务在AOP中的使用出现错误

### ISSUE THREAD

**Issue by sunshine223** [anjoy8/Blog.Core#112]
![HYFUEC`PHVQ1) G3DC1LD29](https://user-images.githubusercontent.com/62974678/93153535-0b68d080-f734-11ea-890d-b851cf89b499.png)

**Comment by anjoy8** [comment]
这是良性错误，就是除0而已，故意写的
没有异常，怎么回滚。

**Comment by sunshine223** [comment]
是在你的接口上测试的，你部署出来的接口 http://apk.neters.club/index.html




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "anjoy8/Blog.Core"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月15日(星期二) 中午11:52
收件人:&nbsp;"anjoy8/Blog.Core"<Blog.Core@noreply.github.com&gt;;
抄送:&nbsp;"🌾"<1083471683@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [anjoy8/Blog.Core] 事务在AOP中的使用出现错误 (#112)





 
Closed #112.
