### ISSUE TITLE
工作单元管理事务，多次请求后出现锁表

### ISSUE THREAD

**Issue by 18310880751** [anjoy8/Blog.Core#116]
测试数据库为Oracle
使用工作单元管理事务（包括AOP的方式），通过多次请求后有可能出现锁表的情况。

修改IsShardSameThread的配置为true后，能解决锁表的问题。跨仓事务也同样能解决问题。

**Comment by awentop** [comment]
我使用的sql server,使用aop事务同样多次请求之后出现锁表情况，去掉事务就正常了

**Comment by YannKing** [comment]
> 我使用的sql server,使用aop事务同样多次请求之后出现锁表情况，去掉事务就正常了

我以为只有我遇到这个问题，不知道怎么解决。。。

**Comment by awentop** [comment]
> > 我使用的sql server,使用aop事务同样多次请求之后出现锁表情况，去掉事务就正常了
> 
> 我以为只有我遇到这个问题，不知道怎么解决。。。

去掉事务就没再锁住过了，但是感觉在裸奔

**Comment by anjoy8** [comment]
1、我一直在用没遇到
2、该issue作者不是说了么 ，IsShardSameThread的配置为true
3、没说一定要使用AOP事务，你可以使用正常的try catch
4、用efcore
