### ISSUE TITLE
关闭所有菜单无效

### ISSUE THREAD

**Issue by o-skyworth** [anjoy8/Blog.Core#12]
http://123.206.33.109:2364，这个演示地址里面，点击账户侧的关闭所有操作后，界面是关闭了，但是点击刷新又会全部显示出来了？

**Comment by anjoy8** [comment]
ok，我了解了
我是放到了 session 里边了应该是，
我有空看看，然后调整下，再在这里回复你，谢谢

**Comment by anjoy8** [comment]
你好，我已经做好处理了，你可以去看看
