### ISSUE TITLE
恢复计划任务有bug

### ISSUE THREAD

**Issue by yuliang2417535997** [anjoy8/Blog.Core#123]
![image](https://user-images.githubusercontent.com/26182238/96946550-44564b00-1513-11eb-8633-02996726d5a7.png)

这里如果是恢复暂停的任务，应该使用   await _scheduler.Result.ResumeJob(jobKey);  如果是重启任务，请添加取消立即启动的代码
TriggerKey triggerKey = new TriggerKey(tasksQz.Id.ToString(), tasksQz.JobGroup);

**Comment by yuliang2417535997** [comment]
上面取消立即启动的代码应该是  这个  ((CronTriggerImpl)trigger).MisfireInstruction = MisfireInstruction.CronTrigger.DoNothing;

**Comment by anjoy8** [comment]
感谢已采纳
