### ISSUE TITLE
关于Repository层报错无法捕捉的问题

### ISSUE THREAD

**Issue by weiwoducui** [anjoy8/Blog.Core#126]
在Service层使用Repository层的QueryById方法来获取对应的实体对象，发生错误，错误为调用目标发生异常。后来检查发现是实体的主键 没有加上 [SugarColumn(IsPrimaryKey = true)] 特性导致。如果在Repository层的QueryById方法中使用try catch就能捕捉到具体错误。请问有什么办法能够捕捉到具体的错误而不是调用目标发生异常这种宽泛的错误，不好排错

**Comment by weiwoducui** [comment]
`我发现只要关闭掉BlogLogAOP就能够捕捉到具体错误 =>"Queryable.In(params object[] pkValues): Only one primary key" .但是如果开启BlogLogAOP的话就会捕捉不到。我感到十分疑惑，因为如果我单独使用代码在仓储层跑出异常的话是能够在BlogLogAOP的catch中捕捉到错误。

**Comment by anjoy8** [comment]
这是肯定的，因为包裹了一次，你可以把aop关闭，
也可以统一用aop的异常来记录日志

**Comment by weiwoducui** [comment]
> 这是肯定的，因为包裹了一次，你可以把aop关闭，
> 也可以统一用aop的异常来记录日志

但是BlogLogAop中页无法捕捉到使用orm操作发生的错误。只能捕捉到普通的代码异常。orm发生的异常感觉就像被吃了一样

**Comment by weiwoducui** [comment]
我明白了，这个异常错误是发生在
    public static async Task<T> AwaitTaskWithPostActionAndFinallyAndGetResult<T>(Task<T> actualReturnValue, Func<object, Task> postAction, Action<Exception> finalAction)
        {
            Exception exception = null;
            try
            {
                var result = await actualReturnValue;
                await postAction(result);
                return result;
            }
            catch (Exception ex)
            {
                exception = ex;
                throw;
            }
            finally
            {
                finalAction(exception);
            }
        }
方法的异常捕捉中而不是在下面这个异常中，怪不得我一直捕捉不到错误。谢谢作者大大解答    
invocation.ReturnValue = InternalAsyncHelper.CallAwaitTaskWithPostActionAndFinallyAndGetResult(
                         invocation.Method.ReturnType.GenericTypeArguments[0],
                         invocation.ReturnValue,
                         //async () => await TestActionAsync(invocation),
                         ex =>
                         {
                             LogEx(ex, ref dataIntercept);
                         });

**Comment by anjoy8** [comment]
是的，恭喜你看明白了
