### ISSUE TITLE
有利用这个项目完成一个完整的博客的案例吗

### ISSUE THREAD

**Issue by chenxianghuan** [anjoy8/Blog.Core#128]
想观摩观摩

**Comment by anjoy8** [comment]
<div style="margin: 20px;color: black; ">
   在线Demo集合: 
   <br>
   <span style="font-size: 10px;color: #5e5d5dba;"></span> 
   <a href="http://www.neters.club" style="color: #159fe6;" target="_blank;"> <img src="http://www.neters.club/favicon.ico" style="float: left;width: 30px;margin-right: 5px;"> www.neters.club</a> 
   <div style="border-bottom: 1px dashed silver; margin: 5px 0;"></div> 
   <a href="http://apk.neters.club/.doc/" style="color: #159fe6;" target="_blank;"> <img src="http://apk.neters.club/logo/favicon-32x32.png" style="float: left;width: 30px;margin-right: 5px;"> apk.neters.club</a> 
   <div style="border-bottom: 1px dashed silver; margin: 5px 0;"></div> 
   <a href="http://vueadmin.neters.club/.doc/" style="color: #159fe6;" target="_blank;"> <img src="http://vueadmin.neters.club/favicon.ico" style="float: left;width: 30px;margin-right: 5px;"> vueadmin.neters.club</a> 
   <div style="border-bottom: 1px dashed silver; margin: 5px 0;"></div> 
   <a href="http://tibug.neters.club/" style="color: #159fe6;" target="_blank;"> <img src="http://tibug.neters.club/favicon.ico" style="float: left;width: 30px;margin-right: 5px;"> tibug.neters.club</a> 
   <div style="border-bottom: 1px dashed silver; margin: 5px 0;"></div> 
   <a href="http://vueblog.neters.club/" style="color: #159fe6;" target="_blank;"> <img src="http://vueblog.neters.club/favicon.ico" style="float: left;width: 30px;margin-right: 5px;"> vueblog.neters.club</a> 
   <div style="border-bottom: 1px dashed silver; margin: 5px 0;"></div> 
    
   <div style="border-bottom: 1px dashed silver; margin: 5px 0;"></div> 
   <a href="http://ids.neters.club/" style="color: #159fe6;" target="_blank;"> <img src="http://ids.neters.club/favicon.ico" style="float: left;width: 25px;margin-right: 7px;margin-top: 1px;margin-left: 3px;"> ids.neters.club</a> 
   <div style="border-bottom: 1px dashed silver; margin: 5px 0;"></div> 
   <a href="http://mvp.neters.club/" style="color: #159fe6;" target="_blank;"> <img src="http://mvp.neters.club/favicon.ico" style="float: left;width: 25px;margin-right: 7px;margin-top: 1px;margin-left: 3px;"> mvp.neters.club</a> 
   <div style="border-bottom: 1px dashed silver; margin: 5px 0;"></div> 
    
   <div style="border-bottom: 1px dashed silver; margin: 5px 0;"></div> 
   <a href="http://jenkins.neters.club/" style="color: #159fe6;" target="_blank;"> <img src="http://jenkins.neters.club/favicon.ico" style="float: left;width: 25px;margin-right: 7px;margin-top: 1px;margin-left: 3px;"> jenkins.neters.club</a> 
   <div style="border-bottom: 1px dashed silver; margin: 5px 0;"></div> 
  </div>
