### ISSUE TITLE
升级到.net5，数据库为Oracle，运行抛出链接数据库失败的异常，退回到.netcore 3.1能正常连接到数据库

### ISSUE THREAD

**Issue by 18310880751** [anjoy8/Blog.Core#129]
升级到.net5，数据库为Oracle，运行抛出链接数据库失败的异常，退回到.netcore 3.1能正常连接到数据库。

异常信息如下：
System.AggregateException:“One or more errors occurred. (English Message : Connection open error . Exception has been thrown by the target of an invocation.
Chinese Message :  连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，实在找不到原因请先Google错误信息：Exception has been thrown by the target of an invocation..)”

另外创建了一个.net5的控制台程序，使用相同的数据库连接字符串，能正常运行。

**Comment by anjoy8** [comment]
![图片](https://user-images.githubusercontent.com/28941816/99047827-bc260b80-25cf-11eb-8ecd-9f31b4a19548.png)

你已经与SqlSugar作者取得联系，他们跟进吧

**Comment by anjoy8** [comment]
不使用SqlSugar，使用原生的Connection尝试下是否可行，
比如这样：
```
 var _connectionString = "";
 using (var connection = new OracleConnection(_connectionString))
 {
     connection.Open();
 }

```

然后把错误代码发出来

**Comment by anjoy8** [comment]
问题已解决
https://mp.weixin.qq.com/s/Y7zxMKJ1HuJtC4ltQQpHKw
