### ISSUE TITLE
MySql.Data.dll Nuget更新到 6.10.4 版本的(Core 2.0只支持当前版本), 再检查连接字符串是否正确

### ISSUE THREAD

**Issue by o-skyworth** [anjoy8/Blog.Core#13]
运行后报错这个，SqlSugar.SqlSugarException:“MySql.Data.dll Nuget更新到 6.10.4 版本的(Core 2.0只支持当前版本), 再检查连接字符串是否正确，Unable to connect to any of the specified MySQL hosts.”，您好，请问下这个要怎么改下哪里啊，mysql连接字符串已经改过了

**Comment by anjoy8** [comment]
你好，你可以先更新下最新的代码，看看，如果还报错，
就把 model 层的 nuget 包，降级到 6.10.4 吧

**Comment by newlifes01** [comment]
有可能是SqlSugar版本的问题，升级为最新版就OK

**Comment by o-skyworth** [comment]
> 
> 
> 你好，你可以先更新下最新的代码，看看，如果还报错，
> 就把 model 层的mysql.data nuget 包，降级到 6.10.4 吧

非常感谢楼主的回答，我把SqlSugar升级最新版本就可以了

**Comment by o-skyworth** [comment]
> 
> 
> 有可能是SqlSugar版本的问题，升级为最新版就OK

非常感谢您的回答，升级最新版本就可以了

**Comment by yangpengflag** [comment]
> > 有可能是SqlSugar版本的问题，升级为最新版就OK
> 
> 非常感谢您的回答，升级最新版本就可以了

请问下怎么升级呢，谢谢，
