### ISSUE TITLE
请问.net 5的程序如何在iis上发布

### ISSUE THREAD

**Issue by huangyun802203** [anjoy8/Blog.Core#130]
在iis上发布后就报500.19的错误，试了很多的办法都不行，.net core 3.1的时候是没有问题的，不知道怎么办了，求大神能够帮忙，谢谢

**Comment by anjoy8** [comment]
我这里没问题，你什么都没提供，我不清楚

**Comment by anjoy8** [comment]
我这边测试两边都没问题，看文章吧，IIS部分：
https://www.cnblogs.com/laozhang-is-phi/p/13964949.html#autoid-1-4-0
