### ISSUE TITLE
请问[SugarColumn] NVarChar长度如何设置为MAX？ 

### ISSUE THREAD

**Issue by IamOscar5** [anjoy8/Blog.Core#131]
[SugarColumn(ColumnDataType = nameof(SqlDbType.NVarChar), Length = ？？？, IsNullable = false)]

请问[SugarColumn] NVarChar长度如何设置为MAX？

**Comment by anjoy8** [comment]
[SugarColumn(ColumnDataType = "nvarchar", Length = int.MaxValue, IsNullable = true)]
