### ISSUE TITLE
多库切换，会出现脏读写(请求时调用，不是运行时调用)

### ISSUE THREAD

**Issue by liuhair** [anjoy8/Blog.Core#134]
public class BaseRepository<TEntity> : IBaseRepository<TEntity> where TEntity : class, new()
    {
        private readonly IUnitOfWork _unitOfWork;
        private SqlSugarClient _dbBase;

        private ISqlSugarClient _db
        {
            get
            {
                /* 如果要开启多库支持，
                 * 1、在appsettings.json 中开启MutiDBEnabled节点为true，必填
                 * 2、设置一个主连接的数据库ID，节点MainDB，对应的连接字符串的Enabled也必须true，必填
                 */
                if (Appsettings.app(new string[] { "MutiDBEnabled" }).ObjToBool())
                {
                    if (typeof(TEntity).GetTypeInfo().GetCustomAttributes(typeof(SugarTable), true).FirstOrDefault((x => x.GetType() == typeof(SugarTable))) is SugarTable sugarTable && !string.IsNullOrEmpty(sugarTable.TableDescription))
                    {
                        _dbBase.ChangeDatabase(sugarTable.TableDescription.ToLower());
                    }
                    else
                    {
                        _dbBase.ChangeDatabase(MainDb.CurrentDbConnId.ToLower());
                    }
                }

                return _dbBase;
            }
        }

这里_dbBase.ChangeDatabase(MainDb.CurrentDbConnId.ToLower());

MainDb.CurrentDbConnId 是个静态变量，同类型多库切换，会出现脏读写问题

**Comment by anjoy8** [comment]
你好，请问你是在事务中多库处理么？
另外可以提供下异常截图或者详细描述

**Comment by liuhair** [comment]
没有在事物中， 场景是 我有两个数据库， A访问A库，B访问B库， 多次调用，会出现A访问到B库了

**Comment by anjoy8** [comment]
> 
> 
> 没有在事物中， 场景是 我有两个数据库， A访问A库，B访问B库， 多次调用，会出现A访问到B库了

ok，我会跟踪调试下，如果你已经找到了合适的解决方案，可以帮忙提交个PR

**Comment by liuhair** [comment]
我是通过 ActionFilter ，每次前端请求数据时，在Header中 包含 是访问A库/B库，我在想能不能放缓存中， 调用时（_dbBase.ChangeDatabase(MainDb.CurrentDbConnId.ToLower())  从缓存中 取 DbConnId ，不知道可行不

**Comment by anjoy8** [comment]
你可以尝试下，我闲下来也测试测试。

**Comment by liuhair** [comment]
前几天忙了没看，  主要是BaseRepository 层 获取不到 Controller Action的上下文。
我试了一种感觉反人类的操作，把Http请求上下文注入到Repository层，上下文请求信息能拿到



<img width="1092" alt="image" src="https://user-images.githubusercontent.com/10876590/101132096-58788680-3641-11eb-9ce8-953a239e2ce7.png">

**Comment by anjoy8** [comment]
> 
> 
> 前几天忙了没看， 主要是BaseRepository 层 获取不到 Controller Action的上下文。
> 我试了一种感觉反人类的操作，把Http请求上下文注入到Repository层，上下文请求信息能拿到
> 
> <img alt="image" width="1092" src="https://user-images.githubusercontent.com/10876590/101132096-58788680-3641-11eb-9ce8-953a239e2ce7.png">

感觉这个是一个，不是办法的办法，其实按理来说，不应该前端来控制db链接的。
sorry，我最近在找工作，闲下来看看。

**Comment by liuhair** [comment]
嗯嗯，这种处理确实不好。但是因为只有在调用API时候，才能确定访问哪个db（哪个库），或者说能不能用session跟db关联，A用户访问A库，B用户访问B库，我再想想，谢谢

**Comment by anjoy8** [comment]
> 嗯嗯，这种处理确实不好。但是因为只有在调用API时候，才能确定访问哪个db（哪个库），或者说能不能用session跟db关联，A用户访问A库，B用户访问B库，我再想想，谢谢

我好像明白你的需求了，你是在发送http请求的时候，再决定用哪个数据库，
BlogCore多库管理其实是在项目启动的时候就已经确定好了，每一个实体的归属问题，因为是在实体上，增加的特性：
`[SugarTable("PasswordLib", "WMBLOG_MSSQL_2")]`

所以说，你是不是对多库理解上和我的不一样？

**Comment by jiaolimin** [comment]
我好像也遇到这个问题， 我有ABCD四个库，都有Table1表，  在Api调用的时候，在Controller层 才知道 要访问 A/B/C/D库， Repository 层 没办法拿到 Controller层的参数 ，请问有什么好的办法吗 @anjoy8 @liuhair

**Comment by anjoy8** [comment]
> 我好像也遇到这个问题， 我有ABCD四个库，都有Table1表， 在Api调用的时候，在Controller层 才知道 要访问 A/B/C/D库， Repository 层 没办法拿到 Controller层的参数 ，请问有什么好的办法吗 @anjoy8 @liuhair

你这种还是在请求时调用问题，而不是当项目启动的时候都已经规划好了，
可以尝试他的方案，把信息放到httpcontext上下文里。

**Comment by jiaolimin** [comment]
[SugarTable("PasswordLib", "A/B/C/D")] 这种是  ABCD是固定， 怎么才能动态的

**Comment by anjoy8** [comment]
try

https://github.com/anjoy8/Blog.Core/issues/134#issuecomment-738606713

**Comment by jiaolimin** [comment]
把信息放到httpcontext上下文里，Header吗？     Repository 层 怎么取呢，求指点

**Comment by jiaolimin** [comment]
楼上 @liuhair   的方法？  有点。。。   感觉把系统结构弄乱了，  有没有更好的解决办法，咱这个框架是不是 目前不支持这种动态多库？ 感觉这种场景很多

**Comment by jiaolimin** [comment]
@liuhair

**Comment by liuhair** [comment]
不要@了，  你这算是 多租户的场景，不同租户访问不同的库，库里表结构一样， 我也在抽时间尝试其他方法，我这暂时没有更好的办法
