### ISSUE TITLE
请问有没有计划增加EventBus队列消息持久化的功能

### ISSUE THREAD

**Issue by Ren4046** [anjoy8/Blog.Core#135]
如题，请问有没有计划增加EventBus队列消息持久化的功能，想使用EventBus这块的功能，但是没发现对消费者异常处理

**Comment by anjoy8** [comment]
你好，还在跟进中，但不会很快，目前打算做这一块，可以一起开发。
事件总线要用到生产中，肯定要改很多地方，持久化是一块，处理器注入也是一块等等等等。

**Comment by duyanming** [comment]
消息队列持久化，rabbitmq kafka 不是都有吗？

**Comment by anjoy8** [comment]
是的，RabbitMQ配置下就行，可能他问的是具体的方案吧，一般自带的都有

**Comment by Ren4046** [comment]
> 消息队列持久化，rabbitmq kafka 不是都有吗？

或者说是事件的持久化吧，主要是对成功、失败的事件的记录。技术有限，描述的不太准确。

**Comment by duyanming** [comment]
> > 消息队列持久化，rabbitmq kafka 不是都有吗？
> 
> 或者说是事件的持久化吧，主要是对成功、失败的事件的记录。技术有限，描述的不太准确。

了解一下ack，消费端没收到消息mqbroker是不会抛弃消息的，如果你收到了，因业务问题抛了异常，可以自己在消费handler里面捕获这个异常，是否抛弃这条消息触发ack，或者记录日志都可以自己去选择。
