### ISSUE TITLE
net5全局异常日志异常

### ISSUE THREAD

**Issue by guangchliu** [anjoy8/Blog.Core#136]
net5框架的代码全局异常日志进入过滤器执行到_loggerHelper.LogError(json.Message + WriteLog(json.Message, context.Exception));里，但是却不生成日志文件。

**Comment by anjoy8** [comment]
经检查：
目前最新版本，发布后可以正常使用，dev环境确实无法生成到日志，

可以回退到以前的版本：
```
   <PackageReference Include="log4net" Version="2.0.8" />
   <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="3.1.0" />
```

具体的愿意我还在咨询，详情查看：https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/issues/98

**Comment by anjoy8** [comment]
问题已找到，是因为common层下的
```
 <PackageReference Include="log4net" Version="2.0.12" />
```
是`2.0.12`版本，要么回退到 `2.0.8`，要么直接删除即可。

但是同时要保证，日志扩展是`3.1.0`以下版。
```
<PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="3.1.0" />
```
