### ISSUE TITLE
任务调度bug

### ISSUE THREAD

**Issue by awentop** [anjoy8/Blog.Core#138]
当将触发器类型改成0时，即字段TriggerType改为0，启动时((CronTriggerImpl)trigger).MisfireInstruction = MisfireInstruction.CronTrigger.DoNothing;会报转型错误，已经改成放对应if语句里面，另外cron详细规则哪里有

**Comment by anjoy8** [comment]
1、感谢提建议，如果方便，可以提交一个PR，当然，如果麻烦，我会稍后自己提交。
2、cron规则，可以网上搜索下 在线Cron表达式生成器，很常见。
