### ISSUE TITLE
对源码中 UnitOfWork 的疑问

### ISSUE THREAD

**Issue by AjuPrince** [anjoy8/Blog.Core#139]
我看您源码的时候，看有 UseTran 内部使用了UnitOfWork，
```
public interface IAService
{
 [UseTran]
public Task<int> GetResultAsyc();
}

public class ASerive:IAService{
  IBaseRepository <XXX> _dal;
  private readonly IBServive _bS;
  private readonly ICServive _cS;
 public ASerive(){// 构造方法注入
 }
```

```
public async Task<int> GetResultAsyc(){
  //这里先使用 _bs 再使用 _cs 分别执行insert 数据 
  // 在调用 自己的 insert 方法 
  /*
    疑问如下： UOW 借助事务一次性提交变更列表中的所有更改，使用同一上下文
    而在使用 _bs和 _cs 分别 insert 数据的时候，
    会调用它所在的BaseRepository 里的DbContext（是不是破坏了UOW【同一上下文】），这就导致 如果 _bs Insert成功后
   _cs 失败,UOW 提供的事务不会回滚，导致数据不一致
  */
 }
}
```

希望老张解答下？是我对UOW有误解还是我的使用有问题？

**Comment by anjoy8** [comment]
1、[UseTran]特性是在Service层的，不是IService接口层的；
2、IBServive  这里应该是仓储，不是service，参考 TestTranInRepositoryAOP 这个；
3、我调试看的Db实例的ID值是一样的
![图片](https://user-images.githubusercontent.com/28941816/100693056-1217f300-33c7-11eb-9b13-f80c6d622070.png)


问：
你是用的什么办法测试的，还有失败是啥意思

**Comment by AjuPrince** [comment]
我将 标签 打在 Service上后
我ORM使用的是EFCore (Pomelo.EntityFrameworkCore.MySql) 
报错如下：
![image](https://user-images.githubusercontent.com/16829343/100700044-7b076700-33d7-11eb-9ae2-af7280a775f7.png)

**Comment by anjoy8** [comment]
抱歉，没有用EFCore。
