### ISSUE TITLE
mysql  +sqlsugar  时间类型的字段 SugarColumn 设置可空  c#的时间字段不是可空类型

### ISSUE THREAD

**Issue by yeibl** [anjoy8/Blog.Core#14]
环境：sqlsugar+mysql 
`
[SugarColumn(ColumnName = "approval_time", ColumnDescription = "审核时间"**,IsNullable =true**)]
		public DateTime approval_time { get; set; }`
加上特性IsNullable =true  但是 DateTime  没有加？实体查询的时候会导致程序崩溃！是奔溃！不是报错哦！  如果改成 

`
[SugarColumn(ColumnName = "approval_time", ColumnDescription = "审核时间"**,IsNullable =true**)]
		public DateTime? approval_time { get; set; }`
就没有问题

**Comment by anjoy8** [comment]
你好，我之前测试了下，我这边是没有问题的，
也是用的Mysql数据库，你可以pull我最新的代码看看：

1、你先把 Permission model 的 ModifyTime 字段改成这样的
![image](https://user-images.githubusercontent.com/28941816/57204615-73a98d00-6feb-11e9-9ca3-347bfa8aab01.png)

2、我的Mysql数据库，我故意设置了一个 null 的数据
![image](https://user-images.githubusercontent.com/28941816/57204634-976cd300-6feb-11e9-9f72-43a51c486b68.png)

3、结果正常
![image](https://user-images.githubusercontent.com/28941816/57204694-e0bd2280-6feb-11e9-8eb8-a97ab2e1120d.png)
