### ISSUE TITLE
是否可以自定义主键，比如Role表，我想自定义主键为13位长度的36进制

### ISSUE THREAD

**Issue by skyworth365** [anjoy8/Blog.Core#141]
是否可以自定义主键，比如Role表，我想自定义主键13位长度的36进制(0-9、A-Z)，ROLE000000001—ROLE000000009，ROLE00000000A，这样的可以吗

**Comment by anjoy8** [comment]
1、如果你要修改主键，就要都修改了，因为其他地方会有关联，比如关系表，是`int`类型的`Rid`，如果单单修改主键，可能会报错，可以参考我的文档（https://mp.weixin.qq.com/s/byKqblOZb-Yof1T8igAAdg），
我定义泛型主键，你需要全部涉及的表都修改了，修改周期不会超过2~3天。

2、另外，我默认的是`Guid`，你可以把泛型主键设置为 `string`，然后自定义你的主键规则。
