### ISSUE TITLE
log4net 如何设置日志写入数据库

### ISSUE THREAD

**Issue by huangyun802203** [anjoy8/Blog.Core#142]
百度了很多方法都不行，这是我的配置，反正都是不行，所以只能来请教一下大神
![image](https://user-images.githubusercontent.com/69627070/100966622-58588800-3568-11eb-869d-2578e1b24170.png)

**Comment by anjoy8** [comment]
目前没太多时间研究，你可以这么处理：
1、开启Debug，`<log4net debug="true">`，看看具体的错误；
2、换用Nlog或者Serilog

**Comment by huangyun802203** [comment]
谢谢提供思路
