### ISSUE TITLE
分页查询时，建议加上返回数据行数

### ISSUE THREAD

**Issue by skyworth365** [anjoy8/Blog.Core#146]
分页查询时，可以添加返回数据行数，详细见sqlsugar官网
http://www.codeisbug.com/Home/Doc?typeId=1189

**Comment by anjoy8** [comment]
目前就有，
`http://apk.neters.club/api/Blog?page=1`

![image](https://user-images.githubusercontent.com/28941816/102198331-37dfe480-3efd-11eb-9574-5cc6c8f340fc.png)
