### ISSUE TITLE
🎨 Blog.Core 常见问题总结，非BUG

### ISSUE THREAD

**Issue by anjoy8** [anjoy8/Blog.Core#148]
### 1、使用MySql作为持久化数据库
  
-----
MySql版本：5.7+
-----
我正在使用的连接字符串格式：`server=118.25.251.113;Database=blogIdp001;Uid=root;Pwd=Jjz.3344;Port=3096;Allow User Variables=True;`
若是Mysql，生成的数据库字段字符集可能不是utf8的，手动修改下.  
或者删掉数据库，在连接字符串后加上CharSet=UTF8mb4，重新生成数据库.

**Comment by anjoy8** [comment]
### 2、使用Oracle作为持久化数据库

----
我正在使用的连接字符串格式：`Data Source=127.0.0.1/ops;User ID=OPS;Password=123456;Persist Security Info=True;Connection Timeout=60;`  
若是Oracle，可能无法自动创建数据库，自己先手动创建数据库；    
注意`Id`是Oracle的关键字，可以修改下根实体类：`RootEntity.cs`；     
注意可能`Sqlsugar`的特性可能不适合，比如：`ColumnDataType = "nvarchar"`，自行批量替换处理；

**Comment by anjoy8** [comment]
⛳ 1、有任何问题，请先自行更新最新代码调试。
然后再提`issue`。

**Comment by anjoy8** [comment]
### 🎄3、使用MySql作为持久化数据库
  
-----
MySql版本：5.7+
-----
我正在使用的连接字符串格式：`server=xxxxxx;Database=blogIdp001;Uid=root;Pwd=12346;Port=3096;Allow User Variables=True;`
若是Mysql，生成的数据库字段字符集可能不是utf8的，手动修改下.  
或者删掉数据库，在连接字符串后加上CharSet=UTF8mb4，重新生成数据库.

**Comment by anjoy8** [comment]
### ✨4、大量使用数据的时候，建议使用Serilog
  
-----
可以使用项目自写的Helper，也可以使用Serilog，
特别是在大量使用日志的时候，建议使用：
```
// 这种方案也行，用的是Serilog
//SerilogServer.WriteLog("RequestIpInfoLog", new string[] { requestInfo + "," }, false); 
```

**Comment by Myst1615731035** [comment]
在使用VS2022作为IDE时，使用T4模板生成代码，在引用：EnvDTE 依赖时，程序集Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=17.0.0.0会导致错误，会提示：程序集“Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”中的类型“Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItem”未标记为可序列化

处理方案：
在 ModelAuto.ttinclude文件下，查找
![image](https://user-images.githubusercontent.com/75727042/169630858-f6b4c807-4cfa-4d93-9092-3208f3aa0851.png)
code:  EnvDTE.DTE dte = (EnvDTE.DTE)hostServiceProvider.GetService(typeof(EnvDTE.DTE));

修改为：EnvDTE.DTE dte = (EnvDTE.DTE)hostServiceProvider.GetCOMService(typeof(EnvDTE.DTE));
可以修复此错误
处理方法来源：https://qa.1r1g.com/sf/ask/2870036711/
![image](https://user-images.githubusercontent.com/75727042/169630986-f1b268c2-1619-43e5-acf6-f719cdf0034f.png)

**Comment by zzmmin** [comment]
mysql 数据库不能是8.0  否则生成数据库的时候报错, 换成5.7就好了

**Comment by fromEnzo** [comment]
> mysql 数据库不能是8.0 否则生成数据库的时候报错, 换成5.7就好了

请问还有更好的解决方案吗？

**Comment by dvtqinhai** [comment]
> mysql 数据库不能是8.0 否则生成数据库的时候报错, 换成5.7就好了

按照你说的成功了，真开心。

**Comment by NingLiu1998** [comment]
> mysql 数据库不能是8.0 否则生成数据库的时候报错, 换成5.7就好了

我就用的8.0的，生成库和表没什么问题

![image](https://user-images.githubusercontent.com/109678937/214652155-3b493de1-3297-4a11-b826-ee082cbf040e.png)

![image](https://user-images.githubusercontent.com/109678937/214652233-c0001cf4-2ca9-4e08-98b2-c980767e260d.png)

**Comment by Caspersure** [comment]
前端考虑下要不要换成Blazor😂
