### ISSUE TITLE
单元的测试的问题

### ISSUE THREAD

**Issue by lchlfe** [anjoy8/Blog.Core#153]
![image](https://user-images.githubusercontent.com/9328706/104555039-2282e500-5678-11eb-810c-82b019d31af3.png)
![image](https://user-images.githubusercontent.com/9328706/104555071-33cbf180-5678-11eb-81c6-733badfab4cc.png)

**Comment by anjoy8** [comment]
#### 1、学会看日志，不能resolve logger参数，
![image](https://user-images.githubusercontent.com/28941816/104560144-6aa60580-5680-11eb-80d6-f426bbd08aac.png)

注入就行。  

在`DI_Test.cs`的服务注册集合中，注册：
```
IServiceCollection services = new ServiceCollection().AddLogging();
```

#### 2、后续可能还有`Automapper`注册问题，自行注册就行。

#### 3、如果提示表不存在，就配置好db。

**Comment by lchlfe** [comment]
好的，谢谢群大大
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ansonzhang<mailto:notifications@github.com>
发送时间: 2021年1月14日 15:54
收件人: anjoy8/Blog.Core<mailto:Blog.Core@noreply.github.com>
抄送: lchlfe<mailto:lchlfe@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [anjoy8/Blog.Core] 单元的测试的问题 (#153)

1、学会看日志，不能resolve logger参数，

[image]<https://user-images.githubusercontent.com/28941816/104560144-6aa60580-5680-11eb-80d6-f426bbd08aac.png>

注入就行。

在DI_Test.cs的服务注册集合中，注册：

IServiceCollection services = new ServiceCollection().AddLogging();



2、后续可能还有Automapper注册问题，自行注册就行。
3、如果提示表不存在，就配置好db。

―
