### ISSUE TITLE
mysql8.0 分页   asc 问题

### ISSUE THREAD

**Issue by liuyangyi** [anjoy8/Blog.Core#159]
Mysql 8.0 版本 

Task<PageModel<TEntity>> QueryPage(Expression<Func<TEntity, bool>> whereExpression, int intPageIndex = 1, int intPageSize = 20, string strOrderByFileds = null)  中的 字段  (strOrderByFileds  asc )     数据库不支持该语法  切换至mysql5.7 就可以   ，麻烦帮忙提供帮助

**Comment by anjoy8** [comment]
这个问题，可以Sqlsugar的官方提issue。
https://github.com/donet5/SqlSugar/issues/835

或者加他们的群
