### ISSUE TITLE
bug 太多了

### ISSUE THREAD

**Issue by whevether** [anjoy8/Blog.Core#16]
bug太多了。,
线上的权限分配勾选父权限。无法选中子的

**Comment by anjoy8** [comment]
你好，你回答问题就这么武断的么？
那我问你，如果我就想要父级菜单，不想要子级，或者要某几个子级，而不是全部，
你怎么设计，难道还要点击父节点，全选子节点？

**Comment by anjoy8** [comment]
另外，如果发现任何 Bug，可以提出来，
有些bug，并不是你所想象的那么不堪。
