### ISSUE TITLE
开发环境下，接口请求很慢

### ISSUE THREAD

**Issue by mlh1421** [anjoy8/Blog.Core#160]
开发环境下，接口请求很慢，在没有数据库请求下，每次接口请求也在1秒左右，生产环境下会快很多，大约在8ms左右，请问在开发环境下有没有优化方案能使请求变快

**Comment by anjoy8** [comment]
或许是你机器问题，提issue请说明具体情况。
我本地没问题
![image](https://user-images.githubusercontent.com/28941816/106539069-3cf20500-6538-11eb-8744-fd2aa47219b9.png)
