### ISSUE TITLE
不希望拿Model直接當成是Web API的參數，該如何修改呢?

### ISSUE THREAD

**Issue by james0217lin** [anjoy8/Blog.Core#161]
我希望實現SysUserInfoServices的Add和Update有不同的參數，比較符合實際的情況，例如:CreateTime就不該是由呼叫Web API的用戶定義，而是系統自行產生；只想修改User的某個數值。

想請問是否能提供一點修改的想法呢?

還是說得每個User的操作都定義一個Services呢…
public interface ISysUserCreateServices : IBaseServices<UserCreateDto>
public interface ISysUserUpdateServices : IBaseServices<UserUpdateDto>
.
.
.
再麻煩指導，謝謝。

**Comment by anjoy8** [comment]
你说的是参数，其实是Dto的视图模型，你可以自定义完善下项目，
用两个泛型参数：
```
public class SysUserInfoService<Tv, Te> : BaseServices<Tv, Te> where Tv :SysUserInfoViewModel where Te : sysUserInfo,ISysUserInfoServices

public interface ISysUserInfoServices:IBaseServices<SysUserInfoViewModel ,sysUserInfo> { bool DoNothing(); }
```

**Comment by james0217lin** [comment]
@anjoy8 謝謝您的回覆，請問您的意思是在BaseServices實作時做AutoMapper嗎?

**Comment by anjoy8** [comment]
看你的需要，是在具体服务，还是在基类都行
多尝试吧，思路给你了
