### ISSUE TITLE
你好，项目中是在MVC里管理用户的，有考虑将用户功能挪到VUE中吗

### ISSUE THREAD

**Issue by wphubs** [anjoy8/Blog.Core#162]

**Comment by anjoy8** [comment]
不是很明白你的意思，
我有两套，基于ids4的，是在认证中心配置用户，
基于jwt的，就是在blog.admin后台控制。

**Comment by wphubs** [comment]
不好意思，是我描述的不太准确。就是如何使用VUE+API的方式维护ids4的用户呢，把认证中心维护用户功能挪到VUE中

**Comment by anjoy8** [comment]
这个我见别人写过，就是重写ids4的各种api，界面用vue来写，具体的我不打算这么写，无法帮到你。
但是我能肯定的是能写，已经有成品了.
可以参考这个作者的:
https://github.com/DestinyCore/Destiny.Core.Flow.WebUI    
https://github.com/DestinyCore/Destiny.Core.Flow

**Comment by wphubs** [comment]
收到，感谢
