### ISSUE TITLE
对全局异常的疑问

### ISSUE THREAD

**Issue by wangtaoceo** [anjoy8/Blog.Core#168]
我在翻阅源码的时候发现在Blog.Core.Extensions项目下已经有了全局异常中间件ExceptionHandlerMidd，但是在Startup中注释掉了，改成了GlobalExceptionsFilter 不知此处有何用意，是为了测试还是为了提供2种处理方式自行选择？
我自行测试2种处理方式后感觉对于api输出来说，ExceptionHandlerMidd中间件处理后的输出效果要更好，不知道改成GlobalExceptionsFilter是出于设计模式而言还是其他原因？

**Comment by anjoy8** [comment]
提供两个方案，供选择。
没有太多的优劣之处，看个人的习惯。
我个人也倾向于中间件方式。
