### ISSUE TITLE
发现一个奇怪的RequRespLogMildd的问题，不确定是否是BUG

### ISSUE THREAD

**Issue by wangtaoceo** [anjoy8/Blog.Core#172]
项目启动（Ctrl+F5）后，在开启了TranAOP和RequestResponseLog的情况下，
如果Services层中使用了UseTran特性，
```csharp
        [UseTran]
        public async Task<string> TestUow()
        {
            await base.Add(new BlogArticle
            {
                bcategory = "技术博文",
                bcontent = "正文1",
                bRemark = "备注1",
                btitle = "标题1",
                IsDeleted = false
            });
            throw new System.Exception("异常测试");
            await base.Add(new BlogArticle
            {
                bcategory = "技术博文",
                bcontent = "正文1",
                bRemark = "备注1",
                btitle = "标题1",
                IsDeleted = false
            });
            return "";
        }
```
在controller中调用该services执行是没问题的，
```csharp
        [HttpGet]
        public async Task<MessageModel<string>> Test()
        {
            Console.WriteLine($"Controller->Test()");
            await _blogArticleServices.TestUow();
            return new MessageModel<string>
            {
                success = true,
                msg = "成功"
            };
        }
```
但执行完毕后，我在vs2019里面打开RequestResponseLog_1615497373.log文件，并清空内容保存后，在执行一次Test()就出现无法执行的问题，swagger一直在转圈
![image](https://user-images.githubusercontent.com/9128929/110920973-f8d4fa00-8358-11eb-8e1f-0476733db039.png)

![image](https://user-images.githubusercontent.com/9128929/110920531-76e4d100-8358-11eb-964b-71a8a41eacb6.png)
连这句 Console.WriteLine($"Controller->Test()");都无法成功执行，感觉像是被阻塞了，发出任何其他请求都不行，当在控制台中按下回车键后即刻执行完毕。包括Quartz的任务一并都被阻塞了
![image](https://user-images.githubusercontent.com/9128929/110921110-2621a800-8359-11eb-95e2-441b64ae873f.png)
这个问题有时候也不出，在清空日志内容后，鼠标激活控制台程序，在执行Test()很大几率会复现。

**Comment by wangtaoceo** [comment]
F5调试后发现在RequRespLogMildd.cs 的RequestDataLog方法执行到LogLock.OutSql2Log时就无任何反应了，必须在控制台回车才能继续执行。

**Comment by wangtaoceo** [comment]
使用IISExpress启动方式后未出现上述问题，调试和启动均无法复现，可以正常执行

**Comment by anjoy8** [comment]
你可以做个测试:
1，去掉那个日志功能，看看是否正常。
2，若第一步正常，那就换一个日志组件，我也有serilog。
3，若上边两步都不行，再看看效果

**Comment by wangtaoceo** [comment]
我抽空测试下
