### ISSUE TITLE
仅改数据库以及启用ids4配置，token无法正常拿来使用登陆

### ISSUE THREAD

**Issue by aion1998** [anjoy8/Blog.Core#174]
如题，启用ids4后（前后端都配置启用了）
**登录会出现以下问题：**
![LHGBQT)WKN_G52ZKF3H2WA](https://user-images.githubusercontent.com/19725014/112573336-0c876280-8e27-11eb-91b4-8ef0de8a3a3e.png)

**前端配置：**
![image](https://user-images.githubusercontent.com/19725014/112573358-1610ca80-8e27-11eb-83fe-0910c1b200d4.png)

**后端配置：**
![image](https://user-images.githubusercontent.com/19725014/112573398-2e80e500-8e27-11eb-9272-76c27fb2483d.png)

**IDS4**
![image](https://user-images.githubusercontent.com/19725014/112573463-4a848680-8e27-11eb-8fc5-bb179c8653ab.png)

除关键配置外其余代码均为改动

**Comment by aion1998** [comment]
代码拉取日期：2021.3.25
电脑系统：windows 10
![image](https://user-images.githubusercontent.com/19725014/112573663-b7981c00-8e27-11eb-9cb4-6b7830d6bba0.png)

代码编辑器：VS2019最新版
![image](https://user-images.githubusercontent.com/19725014/112573644-aea74a80-8e27-11eb-9b25-e8755d89f4c7.png)

Mysql版本：
![image](https://user-images.githubusercontent.com/19725014/112573706-ce3e7300-8e27-11eb-9213-c9cbeb0a625a.png)

**Comment by anjoy8** [comment]
前端没有配置完，
https://github.com/anjoy8/Blog.Admin/blob/master/src/Auth/applicationusermanager.js

**Comment by aion1998** [comment]
> 前端没有配置完，
> https://github.com/anjoy8/Blog.Admin/blob/master/src/Auth/applicationusermanager.js

感谢，我继续走到了后面，然后遇到了这个问题
![image](https://user-images.githubusercontent.com/19725014/112598748-00f96300-8e4a-11eb-9ae1-96a835b6c389.png)

请问一下为啥会报这个错：Invalid redirect_uri: http://127.0.0.1:2364/callback

我尝试访问过这个地址

**Comment by aion1998** [comment]
![image](https://user-images.githubusercontent.com/19725014/112598876-24bca900-8e4a-11eb-9c96-a93b0516d54e.png)
是 可以访问的

**Comment by aion1998** [comment]
我再检查检查吧，谢谢您

**Comment by anjoy8** [comment]
ids4需要配置客户端
https://ids.neters.club/ClientsManager/index
