### ISSUE TITLE
Task 任务定时每天执行，第二天是准点执行，之后就不执行了

### ISSUE THREAD

**Issue by deweitu** [anjoy8/Blog.Core#176]
![QQ图片20210331113427](https://user-images.githubusercontent.com/51613038/113086853-13421b00-9215-11eb-9e9b-410103103e06.png)
以上是该任务查询信息，是当天定时执行了，第二天就不执行了

**Comment by anjoy8** [comment]
经过调试发现，2021.03.11号提交了一次PR：https://github.com/anjoy8/Blog.Core/commit/f1b21321292ad3ae90989493671c77fd88ea3bbf
这个PR中更新了4个文件，主要是`..\Blog.Core.Tasks\QuartzNet\Jobs\JobBase.cs`、`..\Blog.Core.Extensions\ServiceExtensions\JobSetup.cs` 这两个问题更新，
倒是在docker中，无法自动启动，我目前先回滚了，
![image](https://user-images.githubusercontent.com/28941816/113136644-2e814a80-9256-11eb-8bf0-3dea47964bed.png)


应该没问题，
![image](https://user-images.githubusercontent.com/28941816/113136600-23c6b580-9256-11eb-8106-f053b56fef43.png)

具体还在更新中，你可以看看这几个问题，然后先回上个版本。

**Comment by anjoy8** [comment]
不好意思，忘记回复了，
代码没问题，是数据库的remark字符串长度1000，更新的时候，长度超过限制了，导致每更新到数据库，其实任务还在执行。
