### ISSUE TITLE
有用到，坐标深圳，公司用这套框架来搭的，我目前在学习中

### ISSUE THREAD

**Issue by Purple-sheep1022** [anjoy8/Blog.Core#177]
有用到，坐标深圳，公司用这套框架来搭的，我目前在学习中

**Comment by anjoy8** [comment]
多谢~
可以帮忙写到这一个Issue里~
https://github.com/anjoy8/Blog.Core/issues/75

**Comment by Purple-sheep1022** [comment]
已经写了，老张/社会社会



在 2021-04-17 19:47:39，"ansonzhang" ***@***.***> 写道：

多谢~
可以帮忙写到这一个Issue里~
#75
