### ISSUE TITLE
关于swagger 扩展类中使用日志的方式

### ISSUE THREAD

**Issue by HuoYingCunCunZhang** [anjoy8/Blog.Core#179]
ASP.NET CORE 中已经继承了日志组件 -- ILogger ,并通过注入的方式将配置的日志服务注入到其它服务中。
发现作者在扩展项目（Blog.Core.Extension/Middlewares/SwaggerMidd）中有用到日志组件。
内容如下:

> public static class SwaggerMildd
    {
        private static readonly ILog log = LogManager.GetLogger(typeof(SwaggerMildd));
        public static void UseSwaggerMildd(this IApplicationBuilder app, Func<Stream> streamHtml)
        {
            if (app == null) throw new ArgumentNullException(nameof(app));
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                //根据版本名称倒序 遍历展示
                var ApiName = Appsettings.app(new string[] { "Startup", "ApiName" });
                typeof(ApiVersions).GetEnumNames().OrderByDescending(e => e).ToList().ForEach(version =>
                {
                    c.SwaggerEndpoint($"/swagger/{version}/swagger.json", $"{ApiName} {version}");
                });
                c.SwaggerEndpoint($"https://petstore.swagger.io/v2/swagger.json", $"{ApiName} pet");
                // 将swagger首页，设置成我们自定义的页面，记得这个字符串的写法：{项目名.index.html}
                if (streamHtml.Invoke() == null)
                {
                    var msg = "index.html的属性，必须设置为嵌入的资源";
                    log.Error(msg);
                    throw new Exception(msg);
                }
                c.IndexStream = streamHtml;
                if (Permissions.IsUseIds4)
                {
                    c.OAuthClientId("blogadminjs"); 
                }
                // 路径配置，设置为空，表示直接在根域名（localhost:8001）访问该文件,注意localhost:8001/swagger是访问不到的，去launchSettings.json把launchUrl去掉，如果你想换一个路径，直接写名字即可，比如直接写c.RoutePrefix = "doc";
                c.RoutePrefix = "";
            });
        }
    }

这里总感觉加上日志有些突兀，而且不符合依赖注入的风格，但是在我自己开发的过程中有些时候也有这种两难的时候。
第一：我觉在这种扩展方法中最好不要使用特定的日志框架，否则这个类库被别类库引用的话只能强制安装log4net 日志框架增加无畏的开销，或者和当前调用者使用的日志框架冲突，不太合适。
第二：可以使用统一的ASP.NET CORE 封装的日志框架 ，可在扩展方法中引入ILogger 参数这样就可以避免重新在外面定义一个日志类来用。
第三：建议在这种通用底层库中不要写日志记录错误而是直接抛出异常，在上层捕获异常，或被全局异常捕获器捕获异常。

**Comment by HuoYingCunCunZhang** [comment]
> ASP.NET CORE 中已经继承了日志组件 -- ILogger ,并通过注入的方式将配置的日志服务注入到其它服务中。
> 发现作者在扩展项目（Blog.Core.Extension/Middlewares/SwaggerMidd）中有用到日志组件。
> 内容如下:
> 
> > public static class SwaggerMildd
> > {
> > private static readonly ILog log = LogManager.GetLogger(typeof(SwaggerMildd));
> > public static void UseSwaggerMildd(this IApplicationBuilder app, Func streamHtml)
> > {
> > if (app == null) throw new ArgumentNullException(nameof(app));
> > app.UseSwagger();
> > app.UseSwaggerUI(c =>
> > {
> > //根据版本名称倒序 遍历展示
> > var ApiName = Appsettings.app(new string[] { "Startup", "ApiName" });
> > typeof(ApiVersions).GetEnumNames().OrderByDescending(e => e).ToList().ForEach(version =>
> > {
> > c.SwaggerEndpoint($"/swagger/{version}/swagger.json", $"{ApiName} {version}");
> > });
> > c.SwaggerEndpoint($"https://petstore.swagger.io/v2/swagger.json", $"{ApiName} pet");
> > // 将swagger首页，设置成我们自定义的页面，记得这个字符串的写法：{项目名.index.html}
> > if (streamHtml.Invoke() == null)
> > {
> > var msg = "index.html的属性，必须设置为嵌入的资源";
> > log.Error(msg);
> > throw new Exception(msg);
> > }
> > c.IndexStream = streamHtml;
> > if (Permissions.IsUseIds4)
> > {
> > c.OAuthClientId("blogadminjs");
> > }
> > // 路径配置，设置为空，表示直接在根域名（localhost:8001）访问该文件,注意localhost:8001/swagger是访问不到的，去launchSettings.json把launchUrl去掉，如果你想换一个路径，直接写名字即可，比如直接写c.RoutePrefix = "doc";
> > c.RoutePrefix = "";
> > });
> > }
> > }
> 
> 这里总感觉加上日志有些突兀，而且不符合依赖注入的风格，但是在我自己开发的过程中有些时候也有这种两难的时候。
> 第一：我觉在这种扩展方法中最好不要使用特定的日志框架，否则这个类库被别类库引用的话只能强制安装log4net 日志框架增加无畏的开销，或者和当前调用者使用的日志框架冲突，不太合适。
> 第二：可以使用统一的ASP.NET CORE 封装的日志框架 ，可在扩展方法中引入ILogger 参数这样就可以避免重新在外面定义一个日志类来用。
> 第三：建议在这种通用底层库中不要写日志记录错误而是直接抛出异常，在上层捕获异常，或被全局异常捕获器捕获异常。

不知道说的对不对，只是抱着探讨的心态哈哈！！

**Comment by anjoy8** [comment]
很棒！感谢提出异议，以及自己思考过程。
关于你的问题:
1.任何项目都需要日志框架，这是肯定的，那特定扩展类中，就没必须用其他的手写的记录日志方案，比如自己输出到txt。
2.并没有单独定义类，LogManager是日志框架的。如果你用原生的，就必须才用依赖注入的方式。
当然你也可以尝试从Configure()中间件入口，把日志实例拿进来。
3.抛出异常也可以，那就注意异常中间件如何收录，以及定义好中间件顺序，具体看我的ExceptionHandlerMidd.cs。

**Comment by HuoYingCunCunZhang** [comment]
非常开心大佬能受理！奥里给。。。
