### ISSUE TITLE
api用了一段时间后接口变慢， 将Log日志文件清除后又会变快 这是为啥哦 

### ISSUE THREAD

**Issue by lpleaves123** [anjoy8/Blog.Core#184]
用得.net 5.0 开发， api用了一段时间后接口变慢， 将Log日志文件清除后又会变很快 这是为啥。。

**Comment by anjoy8** [comment]
首先，
1、你用的是我的项目么，近三个月的，我都分日志文件到最大每个1m了，你日志多少？多大？更新频率多少，请描述清楚。
2、开了多少中间件或者其他用到日志的服务？再看看你的接口中是否用到了日志服务，请描述清楚。

**Comment by lpleaves123** [comment]
谢谢大佬。 
1、你用的是我的项目么，近三个月的，我都分日志文件到最大每个1m了，你日志多少？多大？更新频率多少，请描述清楚。
(1)用的Blog.Core 底层框架做的项目开发
(2) 
![image](https://user-images.githubusercontent.com/64133921/117619621-14665080-b1a2-11eb-8c1b-1283d9e4bf6f.png)

(3)现在还在测试环境环境 ，最大日志只有3m多 来自于RequestResponseLog_文件
(4)我打算只启用UseRecordAccessLogsMildd中间吧。

2、开了多少中间件或者其他用到日志的服务？再看看你的接口中是否用到了日志服务，请描述清楚。
(1)
![image](https://user-images.githubusercontent.com/64133921/117619952-7d4dc880-b1a2-11eb-825d-3d7abe489fb3.png)
![image](https://user-images.githubusercontent.com/64133921/117620009-96567980-b1a2-11eb-8435-fd3789f0cc8d.png)


[3、我建议断点调试一下，有时候不一定是日志文件的问题，比如IIS20分钟不操作，就会慢，激活后就快。](url)
（1）我的程序部署在centos7上 。用supervisord进行管理的

**Comment by anjoy8** [comment]
可以，你开了三个日志，都是实时记录日志的，或多或少会占点内存，
特别是RequestResponseLog请求记录日志，这个记录的日志特别多，而且是全量的。

我建议：
1、只保留RecordAccessLogs访问日志；
2、大小设置未1m；
3、看是否有改善，如果有，那就是loghelper不太好，可以用serilog，写法可以参考：
```
  // 自定义log输出
  Parallel.For(0, 1, e =>
  {
      LogLock.OutSql2Log("RequestIpInfoLog", new string[] { requestInfo + "," }, false);
  });

  // 这种方案也行，用的是Serilog
  //SerilogServer.WriteLog("RequestIpInfoLog", new string[] { requestInfo + "," }, false);
```

**Comment by lpleaves123** [comment]
好的。 非常感谢。大佬。这么热情的帮忙 。我试试这个方案 观察一下i

**Comment by lpleaves123** [comment]
// 这种方案也行，用的是Serilog
  //SerilogServer.WriteLog("RequestIpInfoLog", new string[] { requestInfo + "," }, false);    用这个就很快。 接口性能很稳定

**Comment by anjoy8** [comment]
ok，那就统一用这个
