### ISSUE TITLE
是怎么使用事务的？

### ISSUE THREAD

**Issue by cocomilk2012** [anjoy8/Blog.Core#19]
这个系统是怎么使用事务的？UseTran

**Comment by anjoy8** [comment]
你好，思路还是使用 SQLSugar 的自带的事务，当然群里有小伙伴，配合着AOP使用了，也可以。
我这两天也可以融合到项目里，
到时候我再回复你，如果你着急，可以进群，看看他咋写的

**Comment by anjoy8** [comment]
你好，很抱歉，是隔两个月，我才回复了这个事务，我已经写好了，
有一个新的分支，Trans1.0 ，你可以pull下来看看，
对应的文章，我明天会发表。
