### ISSUE TITLE
services层无法使用redis仓储

### ISSUE THREAD

**Issue by guangchliu** [anjoy8/Blog.Core#196]
services层无法引用extensions项目，会造成循环依赖，想在业务层也能使用redis仓储

**Comment by anjoy8** [comment]
那就抽离出来公共层，扩展层是用来帮助api层的

**Comment by guangchliu** [comment]
恩恩，我自己在抽离了，只是想着您是否也考虑着后续别人会用到，所以跟您说一声




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月22日(星期二) 上午10:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [anjoy8/Blog.Core] services层无法使用redis仓储 (#196)





 
那就抽离出来公共层，扩展层是用来帮助api层的

**Comment by anjoy8** [comment]
感谢，如果愿意提交PR，也是很欢迎的
