### ISSUE TITLE
用T4模板生成的服务类中baseDal大小写问题

### ISSUE THREAD

**Issue by kdkler** [anjoy8/Blog.Core#198]
用T4模板生成的服务类中
![image](https://user-images.githubusercontent.com/8179285/124374689-0fb8a700-dcd0-11eb-96dd-aaafc3d0e212.png)
提示 BaseServices中没有定义 baseDal

经过查找发现是 BaseDal 首字母大写，就执行成功，应该是模板错误了。如下图
![image](![QQ截图20210704140609](https://user-images.githubusercontent.com/8179285/124374843-0419b000-dcd1-11eb-801b-8548f0cd579a.png))
建议修改。

做主开发的blogcore项目很棒，感谢分享。

**Comment by anjoy8** [comment]
你好，这个代码已经在两个月前 https://github.com/anjoy8/Blog.Core/commit/d385ac0a07d8a3ceb17753541eb5abcd8095ad23 修改了，请更新最新代码查看。
