### ISSUE TITLE
MySQL数据库项目启动生成的表大小写不规范

### ISSUE THREAD

**Issue by LiuDanK** [anjoy8/Blog.Core#210]
![image](https://user-images.githubusercontent.com/32576900/134792832-99abd7c7-d2ea-435f-925f-ec6a66befdca.png)
小问题，只是看起来挺难受的

**Comment by anjoy8** [comment]
感谢提出建议
经过修改，目前生成的db表已经大驼峰，
c#类还是未修改，因为涉及的重构比较多
