### ISSUE TITLE
可否考虑加一个Mini API或 Mini Web API

### ISSUE THREAD

**Issue by donet6** [anjoy8/Blog.Core#215]
.NET 6 的 ASP.NET Core 有一个新特性—— Mini API或 Mini Web API。  可以加一个玩下不   呵呵

**Comment by anjoy8** [comment]
你说的是简化了Program和Startup是吧，
这个我感觉优先级不是很高，你如果感兴趣，可以改改提交个PR。

**Comment by anjoy8** [comment]
鉴于相关博客教程中都是老的模式，Mini Web API可能会对初学者不友好，暂时不更新了。
