### ISSUE TITLE
您好，如果我有一个CommonController通用方法想调用数据库的存储过程这个要写在哪里呢

### ISSUE THREAD

**Issue by o-skyworth** [anjoy8/Blog.Core#22]
您好，如果我有一个CommonController通用方法想调用数据库的存储过程这个要写在哪里呢

**Comment by anjoy8** [comment]
数据库仓储过程的调用，应该放到 Repository 层，和调用纯的 sql 是一样的，
然后控制器 controller 想怎么调用都可以

**Comment by o-skyworth** [comment]
您好，非常感谢您的回复，放在这里是没问题的，放这里想要用到SqlSugar就只能继承自BaseRepository<TEntity>了，那这样Model、Services/IServices都要加上了吧
