### ISSUE TITLE
编译报错NETSDK1152

### ISSUE THREAD

**Issue by wenchui** [anjoy8/Blog.Core#220]
error NETSDK1152: Found multiple publish output files with the same relative path: ***//Blog.Core.Api/appsettings.json, ***//Blog.Core.Tests/appsettings.json. [***//Blog.Core.Tests/Blog.Core.Tests.csproj]

**Comment by wenchui** [comment]
在.6.0.100环境执行编译

**Comment by anjoy8** [comment]
目前没有发现这个问题，你可以删除Blog.Core.Tests/appsettings.json，再试试

**Comment by wenchui** [comment]
删除后报这个错，.6.0.100环境执行编译，master分支
error MSB3030: Could not copy the file "***//Blog.Core.Tests/appsettings.json" because it was not found. [***//Blog.Core.Tests/Blog.Core.Tests.csproj]

**Comment by anjoy8** [comment]
其实不用删，
测试没问题，具体问题你自己排查吧，不是很清楚

**Comment by wenchui** [comment]
参考如下帖子 https://www.poppastring.com/blog/fixing-error-netsdk1152-after-upgrading-to-net-6
在Blog.Core.Tests/Blog.Core.Tests.csproj中添加如下代码后编译正常
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    _<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>_
    <IsPackable>false</IsPackable>
  </PropertyGroup>

**Comment by anjoy8** [comment]
Good,
你可以提交下PR，可能和具体的编译模式不同，我还没遇到过
