### ISSUE TITLE
框架删除出现的错误

### ISSUE THREAD

**Issue by TracyIverson** [anjoy8/Blog.Core#222]
单删时，根据T4模板生成的文件会报错，框架中原有的微信列表也会报错，错误信息：
```text
'string' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'T' in the generic type or method 'SqlSugar.SqlSugarClient.Deleteable<T>(T)'
```
如果修改`BaseRepository.DeleteById()`内容为
```C#
return await _db.Deleteable<TEntity>.In(id).ExecuteCommandHasChangeAsync();
```
可以正常删除，不会报错。`BaseRepository.DeleteById()`原来的写法，我看了SqlSugar文档是根据实体删除的，所以想问一下是框架的版本问题，还是别的什么原因导致的，**.Net版本5.0，SqlSugar版本5.0.3.4**

**Comment by anjoy8** [comment]
T4模板中的代码，可能有时候偏旧。
可以直接看Controller里的代码案例就行

**Comment by TracyIverson** [comment]
谢谢解答
