### ISSUE TITLE
使用t4模板生成IRepository时出现报错

### ISSUE THREAD

**Issue by qq1176914912** [anjoy8/Blog.Core#226]
详情：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		正在编译转换: 类型“ProjectItem”同时存在于“EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”和“Microsoft.VisualStudio.Interop, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”中	mycore.FrameWork	D:\艾拉\mycore\mycore.FrameWork\ModelAuto.ttinclude	81	
![image](https://user-images.githubusercontent.com/79817742/146904697-4168b902-6d2f-4ee4-914d-c363f4d782a1.png)

**Comment by anjoy8** [comment]
我这里测试没问题，你可以检查
1、是否配置了数据库连接字符串在DbHelper.ttinclude
2、尝试在其他电脑上；
**3、更建议使用Sqlsugar的DbFirst模式，在DbFirstController**

**Comment by qq1176914912** [comment]
大佬，您的视频和现在的项目有所不同，我链接的是mysql 我使用 DbFirstController 有两个问题：1、/api/DbFirst/GetAllFrameFilesByTableNames方法中ConnID（数据库链接名称） 这个具体是指 数据库连接字符串 还是我的表名 还是其他的
2、下面zhge这个截图 有Repository Services和IServices  但是为什么没有 IRepository 那我生成的重新生成的IRepository要放到哪里呢
![image](https://user-images.githubusercontent.com/79817742/146912018-0eb05527-abc4-4315-b818-e5cc741ab662.png)

**Comment by qq1176914912** [comment]
我试了各种 他总是告诉我 不是开发模式
![image](https://user-images.githubusercontent.com/79817742/146915188-98a5ca7e-20e5-4374-9286-24edf2a89458.png)

**Comment by anjoy8** [comment]
1、我的代码案例是SqlServer的，Mysql的配置不一样。看这个文章 https://www.cnblogs.com/laozhang-is-phi/p/9757999.html。

2、开发模式你直接看源码，去掉开发模式限制就行了

**Comment by qq1176914912** [comment]
好的 大佬 我现在已经车成功生成了 但是还是之前的那个问题  下图中 生成的IRepository的类 我应该往哪里移动 图2中其他的都有 就是没有IRepository

![image](https://user-images.githubusercontent.com/79817742/147016600-a3b09b91-ef15-4a36-888f-bb90429f68b6.png)
![image](https://user-images.githubusercontent.com/79817742/147016657-a1b41e79-366a-46d0-be76-9163f5c2f64f.png)

**Comment by qq1176914912** [comment]
没事了大佬 找到了 原来是都放到Repository里面了

**Comment by anjoy8** [comment]
嗯，看我的这个文章
https://mp.weixin.qq.com/s/qzmjNExuMiJ7lRHyF7pKDA

**Comment by qq1176914912** [comment]
好的 麻烦大佬了
