### ISSUE TITLE
mq性能非常低

### ISSUE THREAD

**Issue by yyg1987** [anjoy8/Blog.Core#229]
正常mq每秒写入1w，现在的封装写入速度最高30/s

**Comment by yyg1987** [comment]
200也不对啊，自己写个demo 可以达到10000，用这个框架的vlues里的测试方法压测只能10；

**Comment by anjoy8** [comment]
限流什么的都关了么

**Comment by yyg1987** [comment]
![) A7DE45$1@MACZSMCPD3JB](https://user-images.githubusercontent.com/27849909/149314009-51c08aea-62a4-4df5-b900-c61a44079262.png)

**Comment by yyg1987** [comment]
> 限流什么的都关了么

关了呀，直接用for循环也可以测试啊，那样就没有流量的说法了：这样测试下试试
        [HttpGet]
        [AllowAnonymous]
        public void EventBusTry([FromServices] IEventBus _eventBus, string blogId = "1")
        {
            for (int i = 0; i < 1000000; i++)
            {
                var blogDeletedEvent = new BlogDeletedIntegrationEvent(blogId);

                _eventBus.Publish(blogDeletedEvent);
            }

**Comment by anjoy8** [comment]
不清楚你是如何测试的，我这里是200/s，
在本地测试查询方法：await _blogArticleServices.QueryById(@event.BlogId.ToString());。
![image](https://user-images.githubusercontent.com/28941816/151687975-6f525001-4e65-47dd-aec1-ad3bc693091e.png)

![image](https://user-images.githubusercontent.com/28941816/151687980-5cc2f896-ca57-406c-8ee7-af6bc379f72f.png)


![image](https://user-images.githubusercontent.com/28941816/151687983-d7edf38d-1b11-49c2-b036-5ab11fd545bb.png)

**Comment by anjoy8** [comment]
如果一定要打到一万，可以自己搭建个空项目，copy代码。

**Comment by yyg1987** [comment]
多线程可以



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月30日(周日) 中午1:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [anjoy8/Blog.Core] mq性能非常低 (Issue #229)




 
如果一定要打到一万，可以自己搭建个空项目，copy代码。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by anjoy8** [comment]
恩对，多线程肯定可以，你可以把代码贴出来，让其他有需要的看看，或者提交个pr
