### ISSUE TITLE
控制台调用仓库

### ISSUE THREAD

**Issue by CiKk199XC** [anjoy8/Blog.Core#230]
在控制台中仿造Blog.Core.Tests中的DI_Test注册了服务和仓储，但是使用的时候还是报错
![1642067500578_C2A24FC0-BF6E-4c34-A3D4-997AD58C1DFB](https://user-images.githubusercontent.com/97667828/149307259-09f41692-a64e-4de8-8d0c-0fdc5c3e9160.png)
。### 
![1642067666191_325F8C9A-6476-4d2c-9E22-4508D7F56B07](https://user-images.githubusercontent.com/97667828/149307523-98d2942f-a314-4575-b23a-906f8957e4d0.png)

**Comment by anjoy8** [comment]
这是没有依赖注入，肯定是有问题的
