### ISSUE TITLE
专案结构分层该如何学习 ?

### ISSUE THREAD

**Issue by 11006281** [anjoy8/Blog.Core#231]
如题，Blog.Core 对每个功能进行了结构分层，我尝试从零开始分层，但是完全抓不出相依顺序，例如我新建了专案 abc.Middlewares，但是却无法引入 Microsoft.AspNetCore 包，我知道要依靠解决方案的 ProjectReference 来解决，但是该如何判断哪个专案该相依哪个 ? 有没有方向可以学习，谢谢

或许我可以先从 https://github.com/anjoy8/Blog-EFCore-Sqlite 三层开始学习

**Comment by anjoy8** [comment]
依赖的顺序可以通过项目引用来查看。
如果说你对某块代码/业务不知道放哪里，那就需要先学习下项目每个分层的意义了

**Comment by 11006281** [comment]
@anjoy8 

我已经照着 blog.core 的依赖顺序去相依，例如在 Extensions 中，我想要 using Microsoft.AspNetCore 还是找不到? 我可以理解哪段代码该放在哪层，但是这命名空间不懂为何出不来?
