### ISSUE TITLE
用户表中字段冗余，且命名不规范

### ISSUE THREAD

**Issue by HuoYingCunCunZhang** [anjoy8/Blog.Core#232]
![LU 52P SG%UWC@QSK$HVA%I](https://user-images.githubusercontent.com/46839162/150632132-cc40d494-7c28-4b99-8136-567df3a68945.png)
1. name 和 loginname 重复了。
2. 字段开头小写了。其它都大写。

**Comment by anjoy8** [comment]
嗯，感谢提出问题。
用户表是项目创建之初所创建的，很多不规范之处，鉴于其他人已经用到了，就没有调整。
后期会列入修改计划，项目自带的ORM就可以指定对应的列明。
当然如果你愿意帮忙修改也是很棒的。
