### ISSUE TITLE
service不能注入redis

### ISSUE THREAD

**Issue by wbaoning** [anjoy8/Blog.Core#234]
Redis是放在extension, api引用了extension，所以只能在控制器注入RedisBasketRepository使用redis。service就不能了。我觉得这个可以改进一下，因为很多场景service是需要用到redis的。请问这个可以改进一下吗

**Comment by wbaoning** [comment]
放到common层，发布订阅就不能调用service了，纠结

**Comment by wbaoning** [comment]
> 放到common层，发布订阅就不能调用service了，纠结

放到common层，发布订阅就不能调用service了，纠结

**Comment by anjoy8** [comment]
more info see: https://github.com/anjoy8/Blog.Core/pull/235
