### ISSUE TITLE
QueryTabsPage 参数问题

### ISSUE THREAD

**Issue by wbaoning** [anjoy8/Blog.Core#250]
方法 Task<PageModel> QueryTabsPage<T, T2, TResult>(
Expression<Func<T, T2, object[]>> joinExpression,
Expression<Func<T, T2, TResult>> selectExpression,
Expression<Func<TResult, bool>> whereExpression,
Expression<Func<T, object>> groupExpression,
int intPageIndex = 1,
int intPageSize = 20,
string strOrderByFileds = null) 的条件查询 Expression<Func<TResult, bool>> whereExpression 应该改为 Expression<Func<T, T2, bool>> whereExpression

**Comment by wbaoning** [comment]
方法 Task<PageModel<TResult>> QueryTabsPage<T, T2, TResult>(
            Expression<Func<T, T2, object[]>> joinExpression,
            Expression<Func<T, T2, TResult>> selectExpression,
            Expression<Func<TResult, bool>> whereExpression,
            Expression<Func<T, object>> groupExpression,
            int intPageIndex = 1,
            int intPageSize = 20,
            string strOrderByFileds = null) 的条件查询  Expression<Func<TResult, bool>> whereExpression 应该改为 Expression<Func<T, T2, bool>> whereExpression

**Comment by anjoy8** [comment]
你可以重载一个，但是并不是说这个不能用的，你可以提交个PR，新重载个方法。

**Comment by anjoy8** [comment]
> 

你可以看一下BaseRepository.cs最下边有一个注释的demo代码，参考下他的思路。
Expressionable.Create<ProjectToUser>()
