### ISSUE TITLE
PageModel 优化

### ISSUE THREAD

**Issue by GeekLeo** [anjoy8/Blog.Core#251]
PageModel 中的pageCount 可以自动算出，没有必要每次new的时候进行计算。
public int pageCount => (int)Math.Ceiling((decimal)dataCount / PageSize);

注意：需要将PageSize 设置默认值，否则swagger会报错
public int PageSize { set; get; } = 20;

**Comment by anjoy8** [comment]
很棒，可以提交个PR，贡献下代码。

**Comment by GeekLeo** [comment]
PR #252
