### ISSUE TITLE
在增加用户模块当中，如果原本用户本来是有角色的，现在设置为无角色，服务端的代码，是没有对无角色的用户处理的，里面只判断有角色的内容

### ISSUE THREAD

**Issue by 664028812** [anjoy8/Blog.Core#265]
if (sysUserInfo.RIDs.Count > 0)  我觉得 即使 Rids 数量为零的时候 也该对数据处理，删除改用户所有角色信息， 这样更为合理

**Comment by anjoy8** [comment]
你是对的，业务上应该会有这种需求，删除角色。
你可以简单尝试下修改，然后提交PR，也算是做贡献了
