### ISSUE TITLE
登录构造JWT Token时对某部分代码的疑问

### ISSUE THREAD

**Issue by zxf1939** [anjoy8/Blog.Core#268]
作者您好！感觉构造JWT Token时，查询角色、权限关系的这部分代码（下图标出来的地方）没有作用呀，是我哪里没有想到吗？
![image](https://user-images.githubusercontent.com/36785370/162614783-e5cdd933-2ae4-40df-a9d5-c48b456cd81a.png)

**Comment by anjoy8** [comment]
有作用，鉴权逻辑在PermissionHandler.cs，你可以看看。
之所以登录的时候这么处理，是再次登录的时候，要及时更新，毕竟这个是单例的。

**Comment by zxf1939** [comment]
> 有作用，鉴权逻辑在PermissionHandler.cs，你可以看看。 之所以登录的时候这么处理，是再次登录的时候，要及时更新，毕竟这个是单例的。

哦懂了懂了！👍感谢回复
