### ISSUE TITLE
dotnet new blogcoretpl的时候Model里的GitJsonFileFormat生成错了

### ISSUE THREAD

**Issue by jlcool** [anjoy8/Blog.Core#27]
把自己项目名加到url中了，导致无法下载数据。
dotnet new blogcoretpl生成的项目怎么保证最新？
项目非常好，还有文章配合，学到很多东西，大神！牛逼！🐂🍺！非常感谢。

**Comment by anjoy8** [comment]
已经修复了git文件名被替换的问题，
但是如何做饭blogcoretpl实时更新，我还在考虑中
