### ISSUE TITLE
How to Use cache data query

### ISSUE THREAD

**Issue by mrreddevil2412** [anjoy8/Blog.Core#271]
Can you guide me how to use cache in service query.
EX: IBaseService<User> _dal;

_dal.QueybyID(id).WithCache();
Error :500

**Comment by anjoy8** [comment]
hi,
The code has been updated in this commit. (#271)

**Comment by mrreddevil2412** [comment]
> hi, The code has been updated in this commit. ([2bc4fbf](https://github.com/anjoy8/Blog.Core/commit/2bc4fbf2972cc53c5b9a322b046b8da0fe192a6f))

Thanks bro!
it work 👍 💯

**Comment by mrreddevil2412** [comment]
@anjoy8 . how to delete cache, after CRUD any entity? :(

**Comment by anjoy8** [comment]
It will be automatically deleted, you can test:
Manually modify the database data, and the cache is gone.
