### ISSUE TITLE
在BlogController的delete方法调用   await _blogArticleServices.DeleteById(id); 返回错误

### ISSUE THREAD

**Issue by weiguang3100** [anjoy8/Blog.Core#272]
在BlogController的delete方法调用   await _blogArticleServices.DeleteById(id); 返回如下错误

The type 'int' must be a reference type in order to use it as parameter 'T' in the generic type or method 'SqlSugar.SqlSugarClient.Deleteable<T>(T)'

**Comment by weiguang3100** [comment]
我目前升级一下sqlsugar可以了，或者不升级换一下方法
`  public async Task<bool> DeleteById(object id)
        {
            return await _db.Deleteable<TEntity>().In(id).ExecuteCommandHasChangeAsync();
        }`

**Comment by anjoy8** [comment]
很好，可以帮忙提交个PR，为社区做贡献。

**Comment by weiguang3100** [comment]
> 很好，可以帮忙提交个PR，为社区做贡献。

已提交
