### ISSUE TITLE
如何关闭生成项目生成自带表

### ISSUE THREAD

**Issue by wyz1306** [anjoy8/Blog.Core#279]
5.0版
当置为false时
"SeedDBEnabled": false, //只生成表结构
"SeedDBDataEnabled": false, //false生成表,并初始化数据
运行报错
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Table 'text.tasksqz' doesn't exist)
  Source=System.Private.CoreLib
  StackTrace:
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   在 System.Threading.Tasks.Task`1.get_Result()
   在 Test.Core.Extensions.Middlewares.QuartzJobMiddleware.UseQuartzJobMiddleware(IApplicationBuilder app, ITasksQzServices tasksQzServices, ISchedulerCenter schedulerCenter) 在 D:\Healthit\Test.Core\Test.Core.Extensions\Middlewares\QuartzJobMiddleware.cs 中: 第 25 行
   在 Program.<Main>$(String[] args) 在 D:\Healthit\Test.Core\Test.Core.Api\Program.cs 中: 第 179 行

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]
    Test.Core.Repository.Base.BaseRepository<TEntity>.Query() (位于 BaseRepository.cs 中)
    [外部代码]
    Test.Core.Services.BASE.BaseServices<TEntity>.Query() (位于 BaseServices.cs 中)

内部异常 1:
MySqlException: Table 'text.tasksqz' doesn't exist

**Comment by Linlccc** [comment]
"Middleware.QuartzNetJob.Enabled"节点设置成false
