### ISSUE TITLE
关于EventBus 事件总线服务与RabbitMQ的问题

### ISSUE THREAD

**Issue by hottoy** [anjoy8/Blog.Core#282]
如何创建新的队列。EventBus里参数SubscriptionClientName是对应的队列，整个系统只能有一个队列吗？我尝试向这个队列里增加新的业务，只能增加RoutingKey。我想增加新的队列，如何增加呢？谢谢！

**Comment by tiantianliulang** [comment]
也想知道这个问题的解决方案，请问近期有考虑这个issue嘛
