### ISSUE TITLE
.net6.0 发布后IIS部署不成功，老张救急，微信已赞赏，救急拉我微信，谢谢

### ISSUE THREAD

**Issue by EricShen-ESStudio** [anjoy8/Blog.Core#283]
.net6.0版本，发布后，本地执行***.exe文件可以正常运行，swaggger可以正常显示，并能你能顺利访问，用前端vue可以正常登录；
但是发布到IIS后，swagger半天不出来，浏览器访问发布后的端口需要很久，然后提示错误502.5，也严格按照你的文档中502.5的处理办法处理了，但是还是不行，救急

**Comment by EricShen-ESStudio** [comment]
老张反应迅速，确实存在这个问题，已经给出了解决方案，赞！
解决方案：
Blog.Core.Api工程文件中移除这段代码： <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
然后再次发布即可

**Comment by keaidefeizao** [comment]
原来如此，我还上网找了一圈都没解决。
