### ISSUE TITLE
升级到net6.0现在最新版本之后无法打印全局异常日志

### ISSUE THREAD

**Issue by guangchliu** [anjoy8/Blog.Core#287]
升级到net6.0现在最新版本之后，运行代码bug，报错等等无法打印全局异常日志

**Comment by anjoy8** [comment]
拉取最新代码，
检查bin文件夹

**Comment by guangchliu** [comment]
昨天刚拉取了最新代码也检查了bin文件夹相应的log4net.config及log4net.dll文件都是存在的，但是就是不能生成全局异常日志




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月10日(星期天) 晚上7:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [anjoy8/Blog.Core] 升级到net6.0现在最新版本之后无法打印全局异常日志 (Issue #287)





 
拉取最新代码，
 检查bin文件夹

**Comment by anjoy8** [comment]
现在可以了么，可以的话就close吧。

**Comment by guangchliu** [comment]
真给力，好了，主要是什么原因引起的呢？开发环境没有日志，发布环境有日志，开发环境倒是不影响了

**Comment by guangchliu** [comment]
已解决
