### ISSUE TITLE
问下，感觉你这个框架，Services层，每个Service只能操作一个实体类，即Repository，这种在实际业务中不可能这么简单吧，一般都是几张表之间的操作，逻辑

### ISSUE THREAD

**Issue by cpy1989** [anjoy8/Blog.Core#30]

**Comment by anjoy8** [comment]
首先我说明下，我的框架中，虽然Service中参数类型参数 T 是一个，但是并不意味着每个service”只能“操作一个Repository！
你可以参考我的 RoleModulePermissionServices.cs 就知道了。
都是采用注入的形式，将其他仓储接口注入进来，

当然你也可以新建一个复合Service，比如TeacherStudentsClassService.cs ，这样直接注入三个仓储接口即可。
