### ISSUE TITLE
开源很不错，这个代码对新手很友好

### ISSUE THREAD

**Issue by guo1737** [anjoy8/Blog.Core#359]
开源很不错，这个代码对新手很友好。但是代码不够精简，冗余太多，希望作者有改进。 还有adminvue的前端代码整合了2套认证，beforeeach 和intercept 那里的代码问题还是比较多的.

**Comment by anjoy8** [comment]
嗯多谢支持鼓励，
冗余代码也是有利有弊，很多新手建议加的Demo，为的就是快速学习，
后期会考虑逐步精简，其实除了controller层，其他的也都做了优化了。
也欢迎一起提交PR，如果公司使用到了，也欢迎盖楼https://github.com/anjoy8/Blog.Core/issues/75

前端项目确实不是很优雅，精力也都放到了后端api。

**Comment by guo1737** [comment]
Thanks
