### ISSUE TITLE
当我使用UseTran在调用基类方法的时候 会出现锁库的情况。

### ISSUE THREAD

**Issue by YuNingOvo** [anjoy8/Blog.Core#360]
![image](https://github.com/anjoy8/Blog.Core/assets/31461209/80e89bc5-f423-4d64-867e-e7bb9ea0e635)
![image](https://github.com/anjoy8/Blog.Core/assets/31461209/ffe1cf6b-19a7-4d1f-be5b-e0d0e5fbc844)

不知道是我用法不对，还是不支持这样的事务。

**Comment by LemonNoCry** [comment]
基于你截图的代码部分，没有看出来你的问题

可以看一下 TransactionController GetTestTranPropagation
压测没有任何问题

**Comment by YuNingOvo** [comment]
> 基于你截图的代码部分，没有看出来你的问题
> 
> 可以看一下 TransactionController GetTestTranPropagation 压测没有任何问题

![image](https://github.com/anjoy8/Blog.Core/assets/31461209/c4283643-72af-4945-a60b-cfcfba4a29d4)
![image](https://github.com/anjoy8/Blog.Core/assets/31461209/c1ca3be8-a200-4aba-9ce3-cca6409a9c50)

我在嵌套事务中引发了异常 无法回滚上层的事务,于是我在上层的事务中 再次引发异常 依然无法回滚上层事务

**Comment by YuNingOvo** [comment]
> 测试正常 ![image](https://private-user-images.githubusercontent.com/33311705/323118948-be2ea274-acba-487f-9b1f-a470dfae1180.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNDY5NjIsIm5iZiI6MTcxMzM0NjY2MiwicGF0aCI6Ii8zMzMxMTcwNS8zMjMxMTg5NDgtYmUyZWEyNzQtYWNiYS00ODdmLTliMWYtYTQ3MGRmYWUxMTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA5Mzc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNThiYTkyNWYzZGJmZWQ0M2NjZGNkZmU4ODc1OTE1NGYwZDRkY2YwMWE1MDRjOThhZThkMTdmOTY3NTQ5NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7K5Ldnd4U_UAuKKT6u3zUuNeFhG1bZHnBj-8GjtrYlk) ![image](https://private-user-images.githubusercontent.com/33311705/323118986-0cbb1884-984a-41b1-97cf-a1608c4aadc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNDY5NjIsIm5iZiI6MTcxMzM0NjY2MiwicGF0aCI6Ii8zMzMxMTcwNS8zMjMxMTg5ODYtMGNiYjE4ODQtOTg0YS00MWIxLTk3Y2YtYTE2MDhjNGFhZGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA5Mzc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NGJiZmM3ZDhhNWExYzIxYTVhMDkyNjAxMzJkMTNhODljMTYwZTU1MDg5MWNhYjgzMTZiNTdlYmYxNDhjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gQCq33br33b3eNHACkbH-OWV-jaCoc5WCBPPo26E82E)
> 
> 两次执行Rollback ![image](https://private-user-images.githubusercontent.com/33311705/323118807-c94a667e-df2e-40d1-beac-81e105ee857c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNDY5NjIsIm5iZiI6MTcxMzM0NjY2MiwicGF0aCI6Ii8zMzMxMTcwNS8zMjMxMTg4MDctYzk0YTY2N2UtZGYyZS00MGQxLWJlYWMtODFlMTA1ZWU4NTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA5Mzc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZDE5MTU4ZDI1MWMyOGQ3M2FiYjIwYmUwMGZhYjg2NDEzY2UyMTc3NDkyZjUxOTczMzBhZTlhZjVkNDU1NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HSoMTz_XG3wh2bDKhg5azDAZ3LZZktgjI7CcFzSoPro)

我调用控制器中的方法时,是正常回滚的。![image](https://github.com/anjoy8/Blog.Core/assets/31461209/1ab1ceb2-a276-4abf-9daf-5b55a529cf21)
当我在定时任务中去调用时，就会出现这种情况。
![image](https://github.com/anjoy8/Blog.Core/assets/31461209/85150317-3674-425e-b9dc-66e386796c53)

**Comment by LemonNoCry** [comment]
复现出该问题，存在死锁
