### ISSUE TITLE
net8.0.10版本兼容问题 会导致缓存扩展类报错无法启动项目 

### ISSUE THREAD

**Issue by wenyebushuo** [anjoy8/Blog.Core#371]
![blogcore 8 0版本兼容问题001](https://github.com/user-attachments/assets/045a2950-88dc-4224-b77c-391ce8e8b0c6)
![blogcore8 0版本兼容问题002](https://github.com/user-attachments/assets/f6d1942d-8232-4635-bc6e-daf7b72ca545)

**Comment by Azhc** [comment]
麻烦问下这个后面怎么解决的，我现在也是这个问题

**Comment by LemonNoCry** [comment]
是否升级了Microsoft.Extensions.Caching.Memory版本?

可能高版本破坏了原本的结构,导致反射无法获取对象

可以先降低版本使用，等优化

**Comment by LemonNoCry** [comment]
新版已解决
