### ISSUE TITLE
Bug with SqlSugarCacheService

### ISSUE THREAD

**Issue by mrreddevil2412** [anjoy8/Blog.Core#373]
When I change data, sqlsugar will also clear the cache and call the Caching.GetAllCacheKeys() function.
When calling that function, an error occurs at the function CreateGetter<TParam, TReturn>(FieldInfo field)
When I debug, field = null
How should I correct it?

![image](https://github.com/user-attachments/assets/2c155567-3091-4306-8700-93697dcb86d0)

![image](https://github.com/user-attachments/assets/f2b05d62-7388-4a17-a9c8-b89db7110201)

![image](https://github.com/user-attachments/assets/e9aeb3f8-df6b-4006-942e-8d235afc81c1)

**Comment by mrreddevil2412** [comment]
After I checked again, there is now an error even when I get the cache list

**Comment by LemonNoCry** [comment]
Have you upgraded the version of Microsoft.Extensions.Caching.Memory?

The higher version may have destroyed the original structure, which needs to be optimized.

**Comment by mrreddevil2412** [comment]
yes, i upgraded new version 
i fixed. Thanks you!
