### ISSUE TITLE
发现一个问题，今天的代码拷下来，打开“权限分配”页面，页面中获取不到数据，后端报错

### ISSUE THREAD

**Issue by Devin-hjc** [anjoy8/Blog.Core#40]
![image](https://user-images.githubusercontent.com/33113941/70675464-3cf3cd80-1cc4-11ea-8123-3f0734a70076.png)

![image](https://user-images.githubusercontent.com/33113941/70675635-a96ecc80-1cc4-11ea-86b9-67bb9219e98a.png)

如上图

**Comment by Devin-hjc** [comment]
数据库用的是代码自动生成的Sqlite

**Comment by anjoy8** [comment]
我的在线 demo 就是最新的代码，并没有发现问题

**Comment by anjoy8** [comment]
我大概猜到了，这个问题，之前有人遇到过，你把
appsettings.json 中的内存缓存打开，设置为true

```
    "MemoryCachingAOP": {
      "Enabled": true
    },
```

**Comment by Devin-hjc** [comment]
好奇是为什么？断点进去其他页面也访问了那中间件，没问题，就“权限分配”这个页面刷新，就异常了

**Comment by anjoy8** [comment]
> 
> 
> 好奇是为什么？断点进去其他页面也访问了那中间件，没问题，就“权限分配”这个页面刷新，就异常了

你把那个缓存加上，再试试
应该是同时操作同一个表了，毕竟permissionhandler.cs 里使用到了  
await RoleModulePermissionServices.GetRoleModule();

你加上缓存看看吧，我再优化一下

**Comment by Devin-hjc** [comment]
好的，了解了，感谢感谢

**Comment by anjoy8** [comment]
关于其他页面不报错，而只有【权限分配】页面报错的情况，基本已经结案了：

因为在【权限分配页】的Mounted钩子启动的时候，同时请求了两个接口api，而恰巧这个时候我们的授权机制PermissionHandler中，也是同时操作了权限表，应该是造成了冲突，所以这里有两个方案：

1、按照上边说的，加上缓存AOP；
2、在Vue页面中使用 .then() 分批次请求：

```
  getRoles() {
      getRoleListPage().then((res) => {
          this.roles = res.data.response.data;
          this.getPermissions();
      });
  },

```
或者接口是无权限的api。
