### ISSUE TITLE
项目在Seed Mysql 数据时候报错。

### ISSUE THREAD

**Issue by anjoy8** [anjoy8/Blog.Core#41]
```
错误信息：

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAULT NULL

```

**Comment by anjoy8** [comment]
【原因】：这个错误是由于model实体层，codefirst 生成数据库的时候，sql语句不支持mysql造成的，多半是多了一个逗号。

【起因】：
为了满足sqlserver支持中文字符，所以在model实体上加上属性：

```
[SugarColumn(Length = 50, IsNullable = true,ColumnDataType ="nvarchar")]
public string CreateBy { get; set; }
```

【结果】：
虽然在Sqlite 和 Sqlserver中正常，但是在Mysql中应该是多了一个 逗号 导致异常 。


【方案】：
目前已经解决，但是如果自己写的时候，不要加这个 ColumnDataType ="nvarchar" 特性即可。

**Comment by binyly** [comment]
那就是说你又要改回去了洛？ 这个 ColumnDataType

**Comment by anjoy8** [comment]
> 
> 
> 那就是说你又要改回去了洛？ 这个 ColumnDataType

我发现了一个规律，就是有一部分有印象，有一部分没有，
经过测试，好像把最后一个 string 类型的 ColumnDataType 去掉，上边的不去掉，依然通过，就是目前我线上的版本。

但是为了防止其他情况，还是都去掉吧。

这个bug还需要深究，虽然这个 nvarchar 并没有太大的影响，毕竟Mysql 没有这个db类型。

**Comment by anjoy8** [comment]
【最终的方案】:
因为sqlsugar初始化mysql数据库的时候，不能指定字符集，所以如果创建数据库乱码的话，自己手动先创建一个utf-8的空数据库吧，然后再生成表和表数据。
