### ISSUE TITLE
关于本项目在并发中出现数据库连接closed的问题。

### ISSUE THREAD

**Issue by anjoy8** [anjoy8/Blog.Core#44]
【用sqlsugr有时候会报Invalid operation. The connection is closed】

【说明】：就是在异步多并发的时候，sugar实例偶尔会出现连接异常，并不是很常见，如果并发达不到一千以上，不用担心这个问题。

【更正】：有人提到这个问题，多半是自己没有更新SqlSugar 5.0.10+版本，请不要使用之前的版本，还一直压测说报错。

如果还不行
【最后的方案】
1、或者每次访问仓储中每一个方法的时候，都new一个实例，这样实例就不会丢失了。比如把BaseRepository的_db换成一个获取实例方法，每次都new一个，或者ISqlsugarclient注入改成services.AddTransient(o =>。
但是这样不利于事务提交，所以我不建议这么操作。

2、当然好像在同步中没有这个问题，想省事儿，改成同步也行。

**Comment by Devin-hjc** [comment]
“把sqlsugarclient生命周期改成transient”

**Comment by Devin-hjc** [comment]
“把sqlsugarclient生命周期改成transient”

**Comment by Devin-hjc** [comment]
“把sqlsugarclient生命周期改成transient”，这个方案，是不是会在涉及事务的使用上会有问题？

**Comment by anjoy8** [comment]
> “把sqlsugarclient生命周期改成transient”，这个方案，是不是会在涉及事务的使用上会有问题？

嗯，这样会影响事务，所以不用这么设置，还是用我的代码就行，基本不用transient这么操作，
关于并发中断，我压测没发现问题，目前更新到Sqlsugar 5.0.10+版本，没有什么中断问题。

**Comment by Devin-hjc** [comment]
好的

**Comment by anjoy8** [comment]
【已完成】
更新sqlsugar 版本是5.0.10+后，未发现此问题。
