### ISSUE TITLE
DbHelper.ttinclude 模板 执行报错

### ISSUE THREAD

**Issue by q87742235** [anjoy8/Blog.Core#45]
DbHelper.ttinclude 下载下来的大小为 14k  --博主认为是 上传文件有问题 待检查

报错如下：正在编译转换: 类、结构或接口成员声明中的标记“this”无效	Blog.Core.FrameWork	
E:\Study\BlogTest\Blog.Core-master (1)\Blog.Core-master\Blog.Core.FrameWork\DbHelper.ttinclude

**Comment by anjoy8** [comment]
已经更新了，重新下载试试吧。
