### ISSUE TITLE
FromBody 方式 提交实体  IPLogMildd.cs 报错

### ISSUE THREAD

**Issue by wlf921** [anjoy8/Blog.Core#47]
楼主发现个错误，如下
测试代码
` public async Task<object> Login([FromBody] LoginModel loginModel)
{

        return new JsonResult(new
                {
                    success = false,
                    message = "msg"
                });
}`
在 IPLogMildd.cs 报错  行 72 
导致进不到方法中

**Comment by anjoy8** [comment]
【未发现异常】

```
  // 测试代码
  [Route("dsdfsdf")]
  [HttpPost]
  [AllowAnonymous]
  public async Task<object> Login333([FromBody] LoginModel loginModel)
  {

      return new JsonResult(new
      {
          success = false,
          message = "msg"
      });

  }

```

你可以直接下载我最新代码，然后调试，或者直接qq群问我。

**Comment by wlf921** [comment]
楼主代码没问题，我在我项目里使用楼主的日志，出现的问题，找到问题是 
`System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
 at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.Server.IIS.Core.WrappingStream.Read(Byte[] buffer, Int32 offset, Int32 count)`
我在 public void ConfigureServices(IServiceCollection services) 里添加了
       ` // If using Kestrel:
            services.Configure<KestrelServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });
            // If using IIS:
            services.Configure<IISServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });
   `
谢谢楼主回复
