### ISSUE TITLE
一个用户多个角色只能获取搜索到的第一个角色的菜单

### ISSUE THREAD

**Issue by zhouhongjie** [anjoy8/Blog.Core#48]
一个用户多个角色只能获取搜索到的第一个角色的菜单
/// <summary>
        /// 获取路由树
        /// </summary>
        /// <param name="uid"></param>
        /// <returns></returns>
  var roleId = ((await _userRoleServices.Query(d => d.IsDeleted == false && d.UserId == 
    uid)).FirstOrDefault()?.RoleId).ObjToInt();
                if (roleId > 0)

**Comment by anjoy8** [comment]
OK，感谢提醒，就是获取一个roleIdList就行，你可以帮忙改改，提交一个PullRequest，
如果不想，我这两天优化一下吧

**Comment by zhouhongjie** [comment]
var roleIds = (await _userRoleServices.Query(d => d.IsDeleted == false && d.UserId == uid)).Select(d => d.RoleId.ObjToInt()).Distinct();
              // if(roleId>0)
                 if (roleIds.Any())
                {
                   // var pids = (await _roleModulePermissionServices.Query(d => d.IsDeleted == false && d.RoleId == roleId)).Select(d => d.PermissionId.ObjToInt()).Distinct();
                    var pids = (await _roleModulePermissionServices.Query(d => d.IsDeleted == false && roleIds.Contains(d.RoleId))).Select(d => d.PermissionId.ObjToInt()).Distinct();

这样可行？

**Comment by anjoy8** [comment]
你可以测试一下，更新最新代码，没问题直接提交吧
