### ISSUE TITLE
疑似发现aop事务存在问题

### ISSUE THREAD

**Issue by SkylerSkr** [anjoy8/Blog.Core#52]
起初是在自己的项目里，使用aop事务出现了This SqlTransaction has completed; it is no longer usable.的问题，后发现是在services层调用多个Repository层方法时，可能在services方法未执行完成的情况下，提交了事务。
后下载了博主的源码。也发现了类似的问题。
![1](https://user-images.githubusercontent.com/41276818/74604280-48fe7000-50f7-11ea-8c0c-4bcbf1cf4c86.png)
这里访问第一个数据访问层方法
![2](https://user-images.githubusercontent.com/41276818/74604281-4b60ca00-50f7-11ea-95db-678ebeab03c2.png)
然后就进了aop，接着断点就开始乱跳
![3](https://user-images.githubusercontent.com/41276818/74604282-4d2a8d80-50f7-11ea-9701-c8e571f5bc54.png)
![4](https://user-images.githubusercontent.com/41276818/74604283-50257e00-50f7-11ea-97d7-60a139256a56.png)
在访问第三个数据访问层方法之前，工作单元就会提交事务(实际上也可能直接跟着图2继续执行下去)
![5](https://user-images.githubusercontent.com/41276818/74604284-51ef4180-50f7-11ea-9fa0-f27fc47572d0.png)
![6](https://user-images.githubusercontent.com/41276818/74604285-53b90500-50f7-11ea-9bb8-623682850098.png)
接着就会报This SqlTransaction has completed; it is no longer usable.的问题
但是在我的项目里数据库操作是会成功的，用的是mssql
怀疑是否有可能是拦截器和service层并行了导致的，因为都是异步方法。
感谢群主开源，对.Net社区做的贡献。

**Comment by scnjzhang** [comment]
if (IsAsyncMethod(invocation.Method))
                    {
                        var result = invocation.ReturnValue;
                        if (result is Task)
                        {
                            Task.WaitAll(result as Task);
                        }
                    }
                    _unitOfWork.CommitTran();
不知道这个地方这样写可以不，初学者，如果有什么错误大神们就不要嘲笑了

**Comment by anjoy8** [comment]
这么写的话，如果在异步service中有异常发生，如果回滚操作呢

**Comment by cd-zhang2020** [comment]
![image](https://user-images.githubusercontent.com/39512639/78746981-d2fde300-799a-11ea-9c73-12173340aa73.png)
![image](https://user-images.githubusercontent.com/39512639/78747026-f4f76580-799a-11ea-8ef3-8734742c4404.png)
WaitAll会等待Seveice里面的方法异常抛出啊

**Comment by anjoy8** [comment]
感觉有戏！Sqlite和SqlServer已经没问题了，Mysql和Oracle还没有测试，让大家测试吧

**Comment by cd-zhang2020** [comment]
我就用的mysql测试了的，mysql也没有问题
