### ISSUE TITLE
基于AOP的Redis缓存

### ISSUE THREAD

**Issue by w405287435** [anjoy8/Blog.Core#61]
在数据insert或update之后，怎么把相关的Redis缓存清理掉呢

**Comment by anjoy8** [comment]
我自己暂时的方案是两个：
1、缓存时间短一些，具体可以自己把握；
2、缓存的key设计的有一定的规则，比如以表名为前缀 User_，如果有写命令的话，就统一执行一个公共方案去清掉以User_开头的cache；
3、其他的你可以问问群里的想法
