### ISSUE TITLE
请问 为何每个Repository(IUnitOfWork unitOfWork) 都要传递这个unitOfWork

### ISSUE THREAD

**Issue by jol5** [anjoy8/Blog.Core#62]
XXXRepository通过反射加入容器，那这个 IUnitOfWork  肯定来源于容器依赖注入，IUnitOfWork 依赖于SqlSugarClient的ADO事务；这种传递是为何？也没见类内部使用啊。
如果想用跨方法事务，直接在构造方法注入即可，开启线程share，难道不传时，直接注入IUnitOfWork  会出问题？

**Comment by anjoy8** [comment]
1、你在哪里直接注入IUnitOfWork？
2、你可以先按照你的思路修改下，看看效果

**Comment by jol5** [comment]
> 1、你在哪里直接注入IUnitOfWork？
> 2、你可以先按照你的思路修改下，看看效果

那在全部respository 构造函数注入unitofwork 是出于什么原因呢？
