### ISSUE TITLE
 i want to  use identity server 4 in project

### ISSUE THREAD

**Issue by pranavpatil19** [anjoy8/Blog.Core#66]
Please help i want to  use identity server 4  in seprate project

Please help how to use

**Comment by anjoy8** [comment]
Do you want to use identityserver4 in the blog.core project?
If so, download the latest code of blog.core and modify the configuration file appsettings. json , startup-> identityserver4-> Enabled, is set to true.

Then download my another project at https://github.com/anjoy8/Blog.IdentityServer

**Comment by pranavpatil19** [comment]
thank you  ... ok i will check this project too


2)if i  dont want to use jwt  and move identity server 4 in another project.
so you guide me which file i have to configure in that project. 

3) i try to seed database .but i get error.can you share database script of this project

**Comment by anjoy8** [comment]
2）You can search for the keyword "ids4和jwt切换" in the project. There are 6 places, which I have configured, which are if and else.
3）What's wrong with the report? What kind of database do you have, Mysql or Sqlserver or Oracle

**Comment by pranavpatil19** [comment]
can you help me

in which scenario i use jwt and ids4 in my project.
can you help me

**Comment by anjoy8** [comment]
If you only have one resource server, you can just use JWT,
But if you have multiple projects, multiple clients, I recommend using ids4
