### ISSUE TITLE
LogAOP 异步代理的第二种方案（同时开启ids4与LogAOP后接口没有响应）

### ISSUE THREAD

**Issue by renrongjun** [anjoy8/Blog.Core#67]
如题，调试的时候执行到AwaitTaskWithPostActionAndFinallyAndGetResult 方法的 await postAction();就直接结束了，请问怎么解决

**Comment by anjoy8** [comment]
我这里没有遇到这个问题，
无论我无状态接口，还是授权接口，都能获取到数据，
直接调试我最新代码，打断点调试，找到具体的问题，我才能回答，

**Comment by renrongjun** [comment]
不是ids4与LogAOP的问题，好像是那个反射方法的问题，我把代码改了下，可以用了
`       public void Intercept(IInvocation invocation)
        {
            string UserName = _accessor.HttpContext?.User?.Identity?.Name;

            //记录被拦截方法信息的日志信息
            var dataIntercept = "" +
                $"【当前操作用户】：{ UserName} \r\n" +
                $"【当前执行方法】：{ invocation.Method.Name} \r\n" +
                $"【携带的参数有】： {string.Join(", ", invocation.Arguments.Select(a => (a ?? "").ToString()).ToArray())} \r\n";

            try
            {
                MiniProfiler.Current.Step($"执行Service方法：{invocation.Method.Name}() -> ");

                if (invocation.Method.ReturnType.IsAsyncType())
                {
                    var task = invocation.Method.Invoke(invocation.InvocationTarget, invocation.Arguments) as Task;
                    invocation.ReturnValue = task;

                    var type = invocation.Method.ReturnType;
                    var resultProperty = type.GetProperty("Result");
                    dataIntercept += ($"【执行完成结果】：{JsonConvert.SerializeObject(resultProperty.GetValue(invocation.ReturnValue))}");
                }
                else
                {
                    invocation.Proceed();

                    dataIntercept += ($"【执行完成结果】：{invocation.ReturnValue}");
                }
            }
            catch (Exception ex)
            {
                //throw ex;
                dataIntercept += ($"【执行完成结果】：方法中出现异常：{ex.Message + ex.InnerException}\r\n");
            }

            Task.Run(() =>
            {
                Parallel.For(0, 1, e =>
                {
                    LogLock.OutSql2Log("AOPLog", new string[] { dataIntercept });
                });
            });

            _hubContext.Clients.All.SendAsync("ReceiveUpdate", LogLock.GetLogData()).Wait();
        }`

**Comment by anjoy8** [comment]
很棒，Great
