### ISSUE TITLE
Exception middle ware with serilog 

### ISSUE THREAD

**Issue by pranavpatil19** [anjoy8/Blog.Core#68]
I am not using Log4 dot net.insted of lo4.net i am using serilog

   private static readonly log4net.ILog log =
        log4net.LogManager.GetLogger(typeof(ExceptionHandlerMidd));

so please help me How to Configure serilog in  Exception middleware

**Comment by anjoy8** [comment]
First, I've encapsulated a method that you can use directly:
```
Serilogserver.writelog ("RequestIpInfoLog", new string[] {requestInfo + ","}, false);
```

The specific logic, you can see F12.

Second, if you want to learn more about how to use serilog, check out my other open source project:
https://github.com/anjoy8/Blog.Live/tree/master/Serilog_Simple

**Comment by pranavpatil19** [comment]
Thank you . 
i am not saving error in log files. i want to save all exception in database. thank you
