### ISSUE TITLE
我在用JWT这步时报了一个错误

### ISSUE THREAD

**Issue by anxiaolei** [anjoy8/Blog.Core#7]
System.ArgumentException:“IDX12709: CanReadToken() returned false. JWT is not well formed: '[PII is hidden]'.
The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.”

**Comment by anjoy8** [comment]
你这个是JWT的格式错误：
1、在线检查是否格式正确：https://jwt.io/#debugger-io
2、你是不是没有配置密钥key？

**Comment by anjoy8** [comment]
3、检查下你的JWT的发行人（audience），生成和校验是否一致，
 U mye have different audience on token generation and validation

**Comment by anjoy8** [comment]
解决了么，解决了我就closed了
