### ISSUE TITLE
Move all Dependency injection rule in one separate file

### ISSUE THREAD

**Issue by pranavpatil19** [anjoy8/Blog.Core#70]
1) why you use autofac DI Cointainer insted of Microsoft's DI provider was much faster than AutoFac

https://ipjohnson.github.io/DotNet.DependencyInjectionBenchmarks/

2) can you explain why you used this in start up file

private List<Type> tsDIAutofac = new List<Type>();
tsDIAutofac.AddRange(assemblysServices.GetTypes().ToList());
            tsDIAutofac.AddRange(assemblysRepository.GetTypes().ToList());
2.2) builder.RegisterAssemblyTypes(Assembly.GetAssembly(typeof(Love)))
                .EnableClassInterceptors()
                .InterceptedBy(cacheType.ToArray());

what is use of Assembly.GetAssembly(typeof(Love) in blog.core project

 2.3)   var assemblysServices = Assembly.LoadFrom(servicesDllFile);
            builder.RegisterAssemblyTypes(assemblysServices)
                      .AsImplementedInterfaces()
                      .InstancePerDependency()
                      .EnableInterfaceInterceptors()//Quote Autofac.Extras.Dynamic Proxy;
                      .InterceptedBy(cacheType.ToArray());//Allows the list of interceptor services to be assigned to registration.

can you explain this two lines in detail
EnableInterfaceInterceptors()//Quote Autofac.Extras.Dynamic Proxy;
                      .InterceptedBy(cacheType.ToArray());//Allows the list of interceptor services to 

and dont want to use autofac .can you help me convert this code to microsoft di

3) please explain me

c.IndexStream = () => GetType().GetTypeInfo().Assembly.GetManifestResourceStream("Blog.Core.index.html");

                c.RoutePrefix = "";

why you write Blog.Core.index.html
and c.RoutePrefix is empty

**Comment by anjoy8** [comment]
1)Autofac has a wealth of features, such as the ability to register services in batches, to reflect and inject entire assembly **dll**, and to support property injection, which is not available in the Microsoft's DI.

2.1)`List tsDIAutofac = new List();` is to get which services have been registered for the current project, you can see the middleware 
`app.UseAllServicesMildd(_services, tsDIAutofac);`

2.2)`Assembly.GetAssembly(typeof(Love) `  To test how to inject a single class separately。

2.3) 
```
EnableInterfaceInterceptors()//Quote Autofac.Extras.Dynamic Proxy;
.InterceptedBy(cacheType.ToArray());//Allows the list of interceptor services to
```
This is to enable **AOP**  functionality, known as dynamic proxy。

3)`write Blog.Core.index.html`  ，So I can write my own logic on the swagger page, like Miniprofiler, which you can find in the index.html file:
```
<script async="async" id="mini-profiler" src="/profiler/includes.min.js?v=4.1.0+c940f0f28d"
        data-version="4.1.0+c940f0f28d" data-path="/profiler/"
        data-current-id="4ec7c742-49d4-4eaf-8281-3c1e0efa8888" data-ids="4ec7c742-49d4-4eaf-8281-3c1e0efa8888"
        data-position="Left"
        data-authorized="true" data-max-traces="5" data-toggle-shortcut="Alt+P"
        data-trivial-milliseconds="2.0" data-ignored-duplicate-execute-types="Open,OpenAsync,Close,CloseAsync">
</script>
```


` c.RoutePrefix is empty`  ,Purpose is that I can directly through the domain name (**http://localhost:8081**) access, without having to enter **http://localhost:8081/swagger**

**Comment by pranavpatil19** [comment]
thank you  buy why you write Blog.Core.index.html.

can i write direactly index.html or https://localhost:8081/index.html.

**Comment by anjoy8** [comment]
1）That's how you get embedded resources by reflection
2）Open whichever you use
3）Just to make it clear, they're the same function
4）`Appsettings.app(new string[] { "DBS", "1", "Connection" }).ObjToString();`
