### ISSUE TITLE
ApiException Middleware  is not fire 

### ISSUE THREAD

**Issue by pranavpatil19** [anjoy8/Blog.Core#71]
1)ApiException Middleware  is not fire in BLog.core

i write own code its working file please check
[Middleware.zip](https://github.com/anjoy8/Blog.Core/files/4524658/Middleware.zip)

in start up file use
            app.UseApiExceptionHandler();  
            // from custom helper assembly
            //app.UseApiExceptionHandler(opts => { opts.AddResponseDetails = AddCustomErrorInfo; });

2) can you tell me  what is defference between

`services.AddMvc(options =>
            {
                options.Filters.Add(new GlobalExceptionsFilter());

            })

 services.AddControllers(o =>
            {
                // Global exception filtering
                o.Filters.Add(typeof(GlobalExceptionsFilter));
  })`

please help me .. if i want to add filter for both api and mvc controlller what should i do

3) Can YOu Explain me 

if i comment GlobalExceptionsFilter and use UseApiExceptionHandler middleware work fine 

but when i use UseApiExceptionHandler middleware and GlobalExceptionsFilter together only 
GlobalExceptionsFilter  trace exception

i dont understand ; what is happening. 
so what is purpose of middleware and global exception.

even middleware can not detect 400 errror why.

**Comment by anjoy8** [comment]
1）Thanks for sharing. Let me have a look
2）These two are the same, there's no difference
3）I don't know how your code is written, why don't you debug breakpoints
