### ISSUE TITLE
框架使用信息收集计划说明书

### ISSUE THREAD

**Issue by anjoy8** [anjoy8/Blog.Core#75]
亲爱的小伙伴们：
Blog.Core项目已经一岁半啦，感谢各位的支持，Star数马上2k了，目前已经成功的将
前端（VUE）— 后端（AspNetCore）—认证（Ids4）—多客户端模式完全打通，
这里老张有个请求，如果你所在的**公司或者组织**用到了，或者是以它为**基本模型来参考**的，
可以在该ISSUE下建楼，格式是：
```
公司：xxxxx科技有限公司；
目前的架构：微服务中作为子服务 / 单体前后端内部管理后台 等；
```
当然，如果你不想留下信息，仅仅写个城市也行：
```
我们使用到了，公司目前在 北京；
```

  
谢谢。—— 老张的哲学MVP

**Comment by 10wangxiaohu** [comment]
有用到，坐标北京

**Comment by liuxinhh** [comment]
有用到，坐标苏州

**Comment by 1744169623** [comment]
有用到，坐标宁波，哈哈公司信息就不暴露了

**Comment by 1744169623** [comment]
哈哈 有用到，坐标宁波

**Comment by SmartforXiaoYuan** [comment]
换了仓储层，借鉴了这个框架，坐标苏州

**Comment by SmartforXiaoYuan** [comment]
> 有用到，坐标苏州

哪里，我也是苏州的

**Comment by zhouxiaole** [comment]
使用了，但不彻底😊，希望早些更新支付，部门数据…等以下三个😊。我是不有些太贪了😊

**Comment by zhouxiaole** [comment]
内蒙古包头

**Comment by 1027197378** [comment]
有用到 坐标南京

**Comment by Sky-ghost** [comment]
准备使用，坐标苏州昆山，希望后面越来越强大

**Comment by julingguyuan** [comment]
有用到，坐标汕头，前几天微信公众号留言过说3号回家上来评论的，结果拖到今天

**Comment by miaokong0724** [comment]
用到了，主要是restful api，坐标郑州

**Comment by renrongjun** [comment]
有用到，山东德州

**Comment by Cabbage-Leon** [comment]
有用到，上海

**Comment by jiushitanzexi** [comment]
有用到  坐标长沙

**Comment by zhouhongjie** [comment]
我使用到坐标漳州

**Comment by mingyouzhu** [comment]
有用到坐标广州

**Comment by skang0401** [comment]
有用到，坐标浙江嘉兴

**Comment by JustMySpace** [comment]
我们使用到了，公司目前在 北京；

**Comment by o-skyworth** [comment]
我们使用到了，坐标深圳

**Comment by zangyx** [comment]
坐标高密

**Comment by anjoy8** [comment]
坐标北京，帮朋友公司开发

**Comment by jchhh912** [comment]
坐标上海，自己小程序

**Comment by q89683495** [comment]
我们使用到了，公司目前在 太仓市；

**Comment by LXQ9527** [comment]
有用到，坐标广州

**Comment by MingHuiJian** [comment]
我们使用到了，坐标深圳

**Comment by chenjiakuan** [comment]
有借鉴大佬的代码，坐标江门。

**Comment by shenghl** [comment]
准备用,坐标杭州

**Comment by weiwoducui** [comment]
现在作为微服务中的节点框架使用，坐标宁波

**Comment by weile0769** [comment]
现在作为微服务中的节点框架使用，坐标广州

**Comment by ACMILANTX** [comment]
现在做为API框架，坐标海口

**Comment by desert1005** [comment]
有用到，坐标：宁波

**Comment by ZenCN** [comment]
有用到，阿里巴巴

**Comment by longletian** [comment]
> 

你不對勁

**Comment by AndyChien1986** [comment]
有用到，坐标：苏州，开发了一套完成的WMS系统，整套框架性能很好，用起来也很简便，值得推荐及学些的一套好框架，希望老张能继续加油，分享知识，辛苦了。

**Comment by ZNZZATGZ** [comment]
有用到，从framework到core vue前后端分离，魔改了个内部管理系统 ，学习到了很多，坐标广州，感谢老张；

**Comment by anjoy8** [comment]
公司：某上市药业公司；
目前的架构：自研系统，打算用`Blog.Core`搭建小程序服务端；
坐标：石家庄

  
  
```
老张：
使用者未提供`Github`账号，委托我待提交。
``

**Comment by ThreeYearsAgo** [comment]
坐标：苏州
从一开始就跟着老张在一步步的搭建了第一个netcore项目，慢慢到生产环境，虽然中间修改了部份内容以满足公司需求，但总体方向还是没有变化，感谢老张的贡献~

**Comment by zp218218** [comment]
仓储非常适合我们公司多库的项目，直接拿来用了。

**Comment by dsfop** [comment]
在武汉有用到，前后端分离，vue还不会，数据库用的是mongodb，其它完全按框架搭的，有用的就copy

**Comment by o-skyworth** [comment]
有用到，坐标广东深圳，vue不太会，只能自己mvc+EasyUI梭哈了，下个就用net core+vue前后端分离了

**Comment by tangshu1672** [comment]
有用到,坐标 广东深圳,目前处于学习和慢慢修改状态.

**Comment by skyworth365** [comment]
公司：深圳市大疆创新科技有限公司；
目前的架构：单体前后端内部管理后台

**Comment by superlibin** [comment]
1：坐标长沙，目前在职技术管理，目前新项目使用框架，直接拿来作为基础框架改造
使用 AspNetCore 前端vue直接使用 vue element admin 作为基础模板 改造
另外
2：公司：湖南辰蓝科技有限公司 单干
也打算改造一份出来，后续做教育培训的产品使用

**Comment by jianweie** [comment]
坐标湖南怀化，目前借助其思想逻辑，抽取了很多组件实现方式，整合在一套即将开源的商城系统后端和接口中。

**Comment by chenjiale1987** [comment]
坐标北京，内部系统使用，很有收获，感谢

**Comment by tanyin2019** [comment]
我们使用到了，公司目前在 上海

**Comment by wang1643329405** [comment]
坐标北京。使用此框架，在此基础上进行扩展做市域治理相关的业务！

**Comment by JiangYueLin7** [comment]
上海,用了此框架的部分,后面自己改了一些

**Comment by aion1998** [comment]
广州，坐标天河富力盈隆广场，小公司，搞HIS的，准备搭个新框架，就用了这个，把ORM换成了freeSql

**Comment by MarkManYUN** [comment]
上海，自学提升自己，希望以后能用在公司项目中，也感谢老张，start鼓励一下

**Comment by zbayp2** [comment]
有用到，坐标南京，感谢老张

**Comment by MiMeLast** [comment]
公司：广西思佰达信息技术有限责任公司；
目前正在学习，考虑以后使用。

**Comment by LanEddie** [comment]
有用到，坐标深圳，感谢老张。

**Comment by charleslovebest** [comment]
有用到，太原，感谢

**Comment by schangxiang** [comment]
有用到 坐标上海，感谢老张

**Comment by lihaogis** [comment]
有用到，合肥，感谢老张！

**Comment by Alencc2015** [comment]
计划要用来做后台服务，前端用vue3.0 + element plus，厦门谦鹭，感谢老张~

**Comment by liupan19911218** [comment]
用来学习很不错啊

**Comment by ydwlovell** [comment]
谢谢老张，刚开始解除ASP.net core  拿来学习。坐标长春

**Comment by lzb66855024** [comment]
谢谢老张, 正在学习中，计划要用来做后台服务，坐标佛山。

**Comment by Chen-wz** [comment]
谢谢老张，花了一个月刷了一篇视频，坐标浙江

**Comment by Purple-sheep1022** [comment]
有用到，坐标深圳，公司用这套框架来搭的，我目前在学习中 (#177)

**Comment by zluckymn** [comment]
有用到，坐标厦门，更换MongoDB数据库

**Comment by tww19861004** [comment]
很棒 自学用的 很不错，虽然公司转java了，但是业务还是在学点.net core

**Comment by desert1005** [comment]
> 哈哈 有用到，坐标宁波

您是宁波哪里的？

**Comment by esinee** [comment]
有用到，坐标上海

**Comment by jianweie** [comment]
坐标湖南怀化，目前借助其思想逻辑，抽取了很多组件实现方式，整合在一套开源的商城系统中。已经开源了。
https://gitee.com/CoreUnion/CoreShop
第一次做开源项目，期盼大神能多多指点。

**Comment by RankinChen** [comment]
在翻源码。从头尝试一次搭建。

**Comment by bossqianjin** [comment]
有用到，坐标南京

**Comment by hufm** [comment]
有用到，坐标深圳

**Comment by ScriptZW** [comment]
又用到，坐标长沙

**Comment by jackChenJing** [comment]
我们使用到了，公司目前在 成都；

**Comment by www5255977** [comment]
我们用到了 坐标杭州！

**Comment by ImGrootZzw** [comment]
有用的，坐标上海

**Comment by zcfeng1113** [comment]
坐标合肥

**Comment by sdmfly** [comment]
有用到，坐标上海

**Comment by huaxinmeng** [comment]
有用到，坐标深圳

**Comment by zhoutuan** [comment]
有在用，坐标湖南长沙

**Comment by zhoutuan** [comment]
有在用，坐标湖南长沙

**Comment by hldsoft** [comment]
在学习，准备使用，湖南梦工厂

**Comment by dongzirun** [comment]
有用到，坐标深圳

**Comment by xutongqing** [comment]
学习Web开发，坐标上海

**Comment by chengleigit** [comment]
坐标中国安徽天鹅湖

**Comment by chengleigit** [comment]
坐标中国安徽天鹅湖

**Comment by binyly** [comment]
有用到，坐标广州

**Comment by mich1234** [comment]
我们使用到了，公司目前在惠州

**Comment by SmartforXiaoYuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by yangzihan960** [comment]
坐标武汉
公司：环胜咨询(百胜服务中心)
目前的架构：前后端都是基于这套框架进行开发的

另外有个问题，不知道有没有大佬可以解答，前端的vue打包后是部署在iis上的，目前发现通过页面请求后台超过两分钟就超时，但是我在iis上设置了超时时间并没有反应，不通过页面的话走swagger是没有超时限制的，应该可以排除后端的问题

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by anjoy8** [comment]
> 坐标武汉 公司：环胜咨询(百胜服务中心) 目前的架构：前后端都是基于这套框架进行开发的
> 
> 另外有个问题，不知道有没有大佬可以解答，前端的vue打包后是部署在iis上的，目前发现通过页面请求后台超过两分钟就超时，但是我在iis上设置了超时时间并没有反应，不通过页面的话走swagger是没有超时限制的，应该可以排除后端的问题

1、首先2分钟确实有些长了，可以优化下，或者使用长连接。
2、超时应该是前端VUE设置的，你可以看看

**Comment by SmartforXiaoYuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by Justin1107-good** [comment]
即将开始用，坐标苏州。
后端准备基于这套框架进行开发。

**Comment by yuhbo** [comment]
坐标吉林长春，前后端都使用，前端进行了魔改。 目前系统运行中。
但是有个问题：
Log文件在1G左右时，会导致IIS内存，CPU占用全部占满。 32G的服务器，w3wp.exe 占用的内存会达到28，9最后卡死。只能重启。目前我们是定期清理log文件夹。
之前联系过作者本人，给出的方案是将日志写入数据库或者使用srilog，非常感谢。
目前准备改成写入数据库。

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by anjoy8** [comment]
> 关注老张的哲学很久了，准备做点对社会有用的免费公益项目，自己搭建起来太麻烦了，就做个伸手党吧！

这个不错呀，我也有公益打算，想法落地了么，我可以免费技术指导，毕竟是公益的，可以的话加我QQ:3143422472

**Comment by tiantianliulang** [comment]
坐标苏州，看了大佬很多文章，前端自己用vue3搭了一套， 后端借鉴了这个框架，DDD分层，SqlSugar也不错，前后端代码一起生成！

**Comment by youchim5527** [comment]
我们使用到了，公司目前在 上海；

**Comment by youchim5527** [comment]
公司：上海智多鱼信息科技有限公司；
目前的架构：目前是Framework的框架，想跟新以下技术栈来满足未来的业务需求，主要看重的是Blog.Core的微服务架构，以及docker+cicd；

**Comment by ss196224** [comment]
公司：徐州扬鱼软件科技有限公司；
目前的架构：API是基于这套框架进行开发的，也用到了Vue的后台管理系统，关注这个框架很久了，非常不错的架构。

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by whh571463234** [comment]
有用到，坐标深圳

**Comment by kenizhou** [comment]
有用到，坐标HK

**Comment by qq402127440** [comment]
有用到，从之前的3.0升级到5.0，坐标上海

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by 773596523** [comment]
我们使用到了，坐标郑州；

**Comment by Mr-wangzj** [comment]
有用到 坐标杭州

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by SmartforXiaoYuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by baozoudeqingchun** [comment]
有用到，坐标石家庄

**Comment by BEIERGEGE** [comment]
公司：成都蓉智汇网络科技有限公司；
目前的架构：API是基于这套框架进行开发的，也用到了Vue的后台管理系统，关注这个框架很久了，非常不错的架构。

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by Coding-Yu** [comment]
有用到 坐标长沙

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by goodjixiang** [comment]
有用到，坐标福州

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by BlazeCheney** [comment]
很有用，坐标上海

**Comment by SmartforXiaoYuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by goodjixiang** [comment]
公司：福州智祥网络科技有限公司；
目前的架构：目前数据总线在用这个框架，关注这个框架很久了。

**Comment by 13477663313** [comment]
有可能会用到，地点杭州

**Comment by SmartforXiaoYuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by gaiwenlin** [comment]
公司：无锡厚驾信息技术有限公司
跟了好多年，看这这个框架不断的完善和变得强大，支持！

**Comment by SmartforXiaoYuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by gloooe** [comment]
公司: 上海比云信息科技有限公司

**Comment by KnightYyj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by tulongchina** [comment]
北京   中交信捷科技有限公司

**Comment by KnightYyj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by huangbin5218** [comment]
有用到，坐标天津

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by MaybeEleven** [comment]
成都：华毅兴达（成都）信息技术有限公司

**Comment by ZenCN** [comment]
长沙 : 蓝思系统集成有限公司

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by leitao97** [comment]
准备用啊，坐标西安。目前正在学习本框架中，不知道有没有相关的指导手册之类的？介绍一下，更便于上手啊。

**Comment by To-Effort** [comment]
借鉴一下坐标杭州

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by kennard-owen** [comment]
已经有项目用在树莓派上了，外企上海

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by chenhaha2016** [comment]
东莞准备使用

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。

**Comment by mrreddevil2412** [comment]
Hello, 
Tôi đến từ VN
Tôi đã học được rất nhiều từ Framework của bạn.
Tôi đã dựa trên dự án của bạn mà phát triển được > 5 dự án của mình rồi

**Comment by dockerliu** [comment]
> Tôi đến từ VN
> Tôi đã học được rất nhiều từ Framework của bạn.
> Tôi đã dựa trên dự án của bạn mà phát triển được > 5 dự án của mình rồi

Tuyệt vời.

**Comment by ruyizhang** [comment]
上海

**Comment by jackChenJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件已经收到，我将尽快给你回复。
