### ISSUE TITLE
token过期问题

### ISSUE THREAD

**Issue by qq357664624** [anjoy8/Blog.Core#78]
token过期时间快到时候，前端会调用刷新token接口  但是虽然调用了 前端还是会自动退出

重现步骤：1： 配置好所有接口 环境等。
                   2：设置token过期时间为3分钟
                   3： 一直点击一个获取数据请求按钮

                   现象：页面退出登录了

**Comment by qq357664624** [comment]
我们本地怎么解决呢？

**Comment by anjoy8** [comment]
![图片](https://user-images.githubusercontent.com/28941816/81379039-f43d2500-913a-11ea-8eee-6090ada113fa.png)

已修复，只需要更新Admin代码即可。https://github.com/anjoy8/Blog.Admin/commit/ff4712804f210cd9d0950fc442c1d314b399290e
