### ISSUE TITLE
Mysql数据库 创建表结构和数据的时候报错

### ISSUE THREAD

**Issue by achaocn** [anjoy8/Blog.Core#79]
English Message : Connection open error . Authentication to host '10.1.20.4' for user 'mysql' using method 'mysql_native_password' failed with message: Access denied for user 'mysql'@'192.168.3.80' (using password: YES)\r\nChinese Message :  连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，实在找不到原因请先Google错误信息：Authentication to host '10.1.20.4' for user 'mysql' using method 'mysql_native_password' failed with message: Access denied for user 'mysql'@'192.168.3.80' (using password: YES)."}

**Comment by anjoy8** [comment]
你这个是数据库的问题，不是项目的问题，排查下吧
