### ISSUE TITLE
开启BlogLogoAop,单库调用sqlserver数据库，查询会一直卡住

### ISSUE THREAD

**Issue by nyl1223** [anjoy8/Blog.Core#81]
开启BlogLogoAop,单库调用sqlserver数据库，查询会一直卡住

**Comment by goalsyang** [comment]
//具体原因暂时未知 修改成这样可用  
 if (IsAsyncMethod(invocation.Method))
                {
                    //Wait task execution and modify return value
                    if (invocation.Method.ReturnType == typeof(Task))
                    {
                        invocation.ReturnValue = InternalAsyncHelper.AwaitTaskWithPostActionAndFinally(
                            (Task)invocation.ReturnValue,
                             async () => await SuccessAction(invocation, dataIntercept),/*成功时执行*/
                            ex =>
                            {
                                LogEx(ex, dataIntercept);
                            });
                    }
                    else //Task<TResult>
                    {
                        //这里修改成这样就ok
                        var type = invocation.Method.ReturnType;
                        var resultProperty = type.GetProperty("Result");
                        dataIntercept += ($"【执行完成结果】：{JsonConvert.SerializeObject(resultProperty.GetValue(invocation.ReturnValue))}");
                        Parallel.For(0, 1, e =>
                        {
                            LogLock.OutSql2Log("LogAOP", new string[] { dataIntercept });
                        });

                    }

                }

**Comment by anjoy8** [comment]
Cool，
不过你这个不就是我写的方案二么，

我跟他说了，他还是说方案一和二都不行，
而且他的sqlite是可以的，多半还是数据库的问题

**Comment by goalsyang** [comment]
> Cool，
> 不过你这个不就是我写的方案二么，
> 
> 我跟他说了，他还是说方案一和二都不行，
> 而且他的sqlite是可以的，多半还是数据库的问题

我就是直接把你的方案二放进去的 但是不能加
invocation.ReturnValue = invocation.Method.Invoke(invocation.InvocationTarget,invocation.Arguments) as Task;
这行代码 你 as Task之后就会出现查询卡住的情况

**Comment by anjoy8** [comment]
> 
> 我就是直接把你的方案二放进去的 但是不能加
> invocation.ReturnValue = invocation.Method.Invoke(invocation.InvocationTarget,invocation.Arguments) as Task;
> 这行代码 你 as Task之后就会出现查询卡住的情况

不要告诉我，你用的同步写法，如果是异步，为啥不能加 `as task` ？

**Comment by goalsyang** [comment]
> > 我就是直接把你的方案二放进去的 但是不能加
> > invocation.ReturnValue = invocation.Method.Invoke(invocation.InvocationTarget,invocation.Arguments) as Task;
> > 这行代码 你 as Task之后就会出现查询卡住的情况
> 
> 不要告诉我，你用的同步写法，如果是异步，为啥不能加 `as task` ？

加了之后报的这个错 One or more errors occurred. (The connection was not closed. The connection's current state is open.) 但我的的连接串是在using里面的

**Comment by anjoy8** [comment]
1、你需要把你的`controller`是如何调用的列出来，如果你是用 `using` 那就魔改了代码，和我的不一样了，所以就不能按照我的写法了；
我看看你是怎么调用`service`的是；

2、如果你去掉了`invocation.ReturnValue = invocation.Method.Invoke(invocation.InvocationTarget,invocation.Arguments) as Task;` 这句话，
那你是用的同步么，要不然怎么获取的返回值，这都要说清楚，不能简单的说这个bug；

**Comment by nyl1223** [comment]
我就是原原本本网上的源代码，我只是在配置文件把BLOGAOP开启来，主数据库换成mssql就不行了

**Comment by nyl1223** [comment]
网上的源代码只是开启 BlogAOP，单数据库，主数据库改为mssql就有问题，不是数据库的问题，换成SQL2012也不行

**Comment by goalsyang** [comment]
> 网上的源代码只是开启 BlogAOP，单数据库，主数据库改为mssql就有问题，不是数据库的问题，换成SQL2012也不行

针对这个问题，又进行了一番魔改，希望作者大大不要介意。现将修改之后的代码贴出:
一:
  else //Task<TResult>
                    {
                        invocation.ReturnValue = InternalAsyncHelper.CallAwaitTaskWithPostActionAndFinallyAndGetResult(
                         invocation.Method.ReturnType.GenericTypeArguments[0],
                         invocation.ReturnValue,
                          //async () => await SuccessAction(invocation, dataIntercept),/*成功时执行*/
                          async (o) => await SuccessAction(o, invocation, dataIntercept),/*成功时执行*/
                         ex =>
                         {
                             LogEx(ex, dataIntercept);
                         });
                    }
二:
        public static object CallAwaitTaskWithPostActionAndFinallyAndGetResult(Type taskReturnType, object actualReturnValue, Func<object,Task> action, Action<Exception> finalAction)
        {
            return typeof(InternalAsyncHelper)
                .GetMethod("AwaitTaskWithPostActionAndFinallyAndGetResult", BindingFlags.Public | BindingFlags.Static)
                .MakeGenericMethod(taskReturnType)
                .Invoke(null, new object[] { actualReturnValue, action, finalAction });
        }
三:将返回的值添加到委托中
        public static async Task<T> AwaitTaskWithPostActionAndFinallyAndGetResult<T>(Task<T> actualReturnValue, Func<object,Task> postAction, Action<Exception> finalAction)
        {
            Exception exception = null;
            try
            {
                var result = await actualReturnValue;
                await postAction(result);
                return result;
            }
            catch (Exception ex)
            {
                exception = ex;
                throw;
            }
            finally
            {
                finalAction(exception);
            }
        }
四:
        private async Task SuccessAction(object o, IInvocation invocation, string dataIntercept)
        {
            invocation.ReturnValue = o;
            var type = invocation.Method.ReturnType;
            if (typeof(Task).IsAssignableFrom(type))
            {
                var resultProperty = type.GetProperty("Result");
                //类型错误 都可以不要invocation参数，直接将o系列化保存到日记中
               // dataIntercept += ($"【执行完成结果】：{JsonConvert.SerializeObject(resultProperty.GetValue(invocation.ReturnValue))}");
                dataIntercept += ($"【执行完成结果】：{JsonConvert.SerializeObject(invocation.ReturnValue)}");
            }
            else
            {
                dataIntercept += ($"【执行完成结果】：{invocation.ReturnValue}");
            }

            await Task.Run(() =>
            {
                Parallel.For(0, 1, e =>
                {
                    LogLock.OutSql2Log("LogAOP", new string[] { dataIntercept });
                });
            });
        }
