### ISSUE TITLE
Inject di autofac

### ISSUE THREAD

**Issue by pranavpatil19** [anjoy8/Blog.Core#88]
`  public class RoleService<Tv, Te> : BaseServices<Tv, Te>
                                                where Tv :RoleViewModel
                                                where Te : Role,IRoleService`

`public interface IRoleServices:IBaseServices<RoleViewModel,Role>
    {
           bool  DoNothing();
    }`

I use   builder.RegisterGeneric(typeof(BaseServices<,>))
                    .As(typeof(IBaseServices<,>)); -Wok fine

 builder.RegisterGeneric(typeof(RoleService<,>))
                    .As(typeof(IRoleService<>)); --registration fail Di 

please help me.. or suggest me any change. where i wrong
i need view model for mapping

**Comment by anjoy8** [comment]
Sorry, I have not used this generic base class registry
