### ISSUE TITLE
t4  模版有没有基于 mysql  的

### ISSUE THREAD

**Issue by yeibl** [anjoy8/Blog.Core#9]
Vschool.FrameWork   T4好像不可以切换数据源，只能mssql  我想用mysql

**Comment by anjoy8** [comment]
你好，有的，具体可以看我的文章
https://www.cnblogs.com/laozhang-is-phi/p/9757999.html#autoid-5-4-0

**Comment by anjoy8** [comment]
是群里小伙伴写的，有疑问可以加群

**Comment by yeibl** [comment]
ok，已解决，非常感谢！
