### ISSUE TITLE
能否在DbFirst 生成4层文件的时候，再生成一下控制器

### ISSUE THREAD

**Issue by liujianfeng1020** [anjoy8/Blog.Core#91]
当数据表OK的时候，使用/api/DbFirst/GetFrameFiles，生成4层文件的时候。
最好能够同时生成对应的controller文件，然后里面包含常用的  增删改查接口。
满足restful的接口即可。
如查询所有，查询单挑记录，创建，更新，删除。

**Comment by anjoy8** [comment]
Done.
