### ISSUE TITLE
关于7/7日下载的最新版本，使用CreateYourProject工具后编译报错的问题

### ISSUE THREAD

**Issue by AndyChien1986** [anjoy8/Blog.Core#94]
通过CreateYourProject生成出来的项目文件，使用Blog.Core.Build编译直接报错，今年3月份下载的版本使用CreateYourProject能正常编译，报错信息如下：

C:\Program Files\dotnet\sdk\3.1.301\NuGet.targets(282,5): error MSB3202: 未找到项目文件“C:\MyGitHub\Blog.Core\.1YourProject\YZ-WMS\YZ_WMS.Api\YZ_WMS.Api.csproj”。 [C:\MyGitHub\Blog.Core\.1YourProject\YZ-WMS\YZ-WMS.sln]
C:\Program Files\dotnet\sdk\3.1.301\NuGet.targets(282,5): error MSB3202: 未找到项目文件“C:\MyGitHub\Blog.Core\.1YourProject\YZ-WMS\YZ_WMS.Model\YZ_WMS.Model.csproj”。 [C:\MyGitHub\Blog.Core\.1YourProject\YZ-WMS\YZ-WMS.sln]
C:\Program Files\dotnet\sdk\3.1.301\NuGet.targets(282,5): error MSB3202: 未找到项目文件“C:\MyGitHub\Blog.Core\.1YourProject\YZ-WMS\YZ_WMS.IRepository\YZ_WMS.IRepository.csproj”。 [C:\MyGitHub\Blog.Core\.1YourProject\YZ-WMS\YZ-WMS.sln]
C:\Program Files\dotnet\sdk\3.1.301\NuGet.targets(282,5): error MSB3202: 未找到项目文件“C:\MyGitHub\Blog.Core\.1YourProject\YZ-WMS\YZ_WMS.Repository\YZ_WMS.Repository.csproj”。 [C:\MyGitHub\Blog.Core\.1YourProject\YZ-WMS\YZ-WMS.sln]....

**Comment by anjoy8** [comment]
经检查，项目不支持 "-" 符号，
项目会自动转换下划线 “_”

**Comment by AndyChien1986** [comment]
非常感谢你的解答，接下来的使用中会注意这些事项的。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ansonzhang<mailto:notifications@github.com>
发送时间: 2020年7月9日 15:48
收件人: anjoy8/Blog.Core<mailto:Blog.Core@noreply.github.com>
抄送: AndyChien1986<mailto:mr.seventh@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [anjoy8/Blog.Core] 关于7/7日下载的最新版本，使用CreateYourProject工具后编译报错的问题 (#94)


经检查，项目不支持 "-" 符号，
项目会自动转换下划线 “_”

―
