### ISSUE TITLE
DbFirst生成到model层代码无法再生成数据库表

### ISSUE THREAD

**Issue by li-yuanba** [anjoy8/Blog.Core#98]
目前FrameSeed.Create_Model_ClassFileByDBTable方法中生成的实体类自定属性不包含 Length以及ColumnDataType属性；
如果字段为string类型没有这两个属性的话数据库表会默认生成类型为varchar类型长度为1到字段；
建议可以使用DbFirst.UseRazorAnalysis 方法 增加Length以及ColumnDataType属性；

``

**Comment by liuqingsong** [comment]
`     db.CurrentConnectionConfig.ConfigureExternalServices.RazorService = new RazorService(db);
// IRazorService 接口实现
db.CurrentConnectionConfig.ConfigureExternalServices.RazorService = new RazorService(db);
//Use Razor Template
db.DbFirst.UseRazorAnalysis("").CreateClassFile("c:\\Demo\\Razor\\");



using RazorEngine;
using RazorEngine.Templating;
using SqlSugar;
using System;
using System.Collections.Generic;
using System.Linq;

namespace OrmTest
{
    public class RazorService : IRazorService
    {
        private static string _classNamespace;
        private static string _defaultRazorClassTemplate =
@"using System;
using System.Linq;
using System.Text;
using SqlSugar;
namespace @Model.Namespace 
{
    ///<summary>
    ///
    ///</summary>
    public partial class @Model.ClassName
    {
           public @(Model.ClassName)(){


           }
 @foreach (var item in @Model.CustormColumns)
   {
         @:/// <summary>
         @:/// Desc:@item.ColumnDescription
         @:/// Default:@item.DefaultValue
         @:/// Nullable:@item.IsNullable
         @:/// </summary>     
         @:@item.PropertyText      
            @:public @item.DataType @item.DbColumnName {get;set;}
    }
}
}";
        SqlSugarClient _sqlSugarClient;
        public RazorService(SqlSugarClient sqlSugarClient, string classNamespace = "Models")
        {
            _sqlSugarClient = sqlSugarClient;
            _classNamespace = classNamespace;
        }
        /// <summary>
        /// 方法实现
        /// </summary>
        /// <param name="razorTemplate"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        public List<KeyValuePair<string, string>> GetClassStringList(string razorTemplate, List<RazorTableInfo> model)
        {
            _defaultRazorClassTemplate = _defaultRazorClassTemplate.Replace("@Model.Namespace", _classNamespace);

            List<CustormRazorTableInfo> _model = GetRazorTableInfoList();
            if (_model != null && _model.Any())
            {
                var result = new List<KeyValuePair<string, string>>();
                foreach (var item in _model)
                {
                    try
                    {
                        item.ClassName = item.DbTableName;//Format Class Name
                        string key = "RazorService.GetClassStringList" + _defaultRazorClassTemplate.Length;
                        var classString = Engine.Razor.RunCompile(_defaultRazorClassTemplate, key, item.GetType(), item).Replace("&quot;","\"");
                        result.Add(new KeyValuePair<string, string>(item.ClassName, classString));
                    }
                    catch (Exception ex)
                    {
                        new Exception(item.DbTableName + " error ." + ex.Message);
                    }
                }
                return result;
            }
            else
            {
                return new List<KeyValuePair<string, string>>();
            }
        }
        /// <summary>
        /// 获取自定义RazorTableInfo,增加PropertyText属性
        /// </summary>
        /// <returns></returns>
        private List<CustormRazorTableInfo> GetRazorTableInfoList()
        {
            List<CustormRazorTableInfo> razorList = new List<CustormRazorTableInfo>();

            foreach (var item in _sqlSugarClient.DbMaintenance.GetTableInfoList())
            {
                var columns = _sqlSugarClient.DbMaintenance.GetColumnInfosByTableName(item.Name, false);
                CustormRazorTableInfo table = new CustormRazorTableInfo()
                {
                    CustormColumns = columns.Select(it => new CustormRazorColumnInfo()
                    {
                        ColumnDescription = it.ColumnDescription,
                        DataType = it.DataType,
                        DbDataType = it.DataType,
                        DbColumnName = it.DbColumnName,
                        DefaultValue = it.DefaultValue,
                        IsIdentity = it.IsIdentity,
                        IsNullable = it.IsNullable,
                        IsPrimarykey = it.IsPrimarykey,
                        Length = it.Length,

                    }).ToList(),
                    Description = item.Description,
                    DbTableName = item.Name
                };
                foreach (var col in table.CustormColumns)
                {
                    col.DataType = GetPropertyTypeName(columns.First(it => it.DbColumnName == col.DbColumnName));
                    if (col.DataType == "string" && col.Length == -1)
                    {
                        col.Length = int.MaxValue;
                    }
                    if (col.DbDataType == "nvarchar" && col.Length != int.MaxValue)
                    {
                        // 处理nvarchar字段长度X2
                        col.Length = col.Length / 2;
                    }
                    // 生成扩展属性
                    col.PropertyText = GetPropertyText(col);
                }
                razorList.Add(table);

            }
            return razorList;
        }

        private string GetPropertyText(CustormRazorColumnInfo item)
        {
            string SugarColumnText = DbFirstTemplate.ValueSugarCoulmn;

            List<string> joinList = new List<string>();
            if (item.IsPrimarykey)
            {
                joinList.Add("IsPrimaryKey=true");
            }
            if (item.IsIdentity)
            {
                joinList.Add("IsIdentity=true");
            }
          
            if (item.DataType == "string")
            {
                joinList.Add("ColumnDataType=\"" + item.DbDataType + "\"" + ", Length =" + item.Length + "");
            }
            if (item.IsNullable)
            {
                joinList.Add("IsNullable=true");
            }
            if (item.ColumnDescription != null && item.ColumnDescription != "")
            {
                joinList.Add("ColumnDescription=\"" + item.ColumnDescription + "\"");
            }
            SugarColumnText = joinList.Count < 1 ? "" : string.Format(SugarColumnText, string.Join(",", joinList));
            return SugarColumnText;
        }

        private string GetPropertyTypeName(DbColumnInfo item)
        {
            string result = item.PropertyType != null ? item.PropertyType.Name : _sqlSugarClient.Ado.DbBind.GetPropertyTypeName(item.DataType);
            if (result != "string" && result != "byte[]" && result != "object" && item.IsNullable)
            {
                result += "?";
            }
            if (result == "Int32")
            {
                result = "int";
            }
            if (result == "String")
            {
                result = "string";
            }
            return result;
        }
    }
    public class CustormRazorColumnInfo : RazorColumnInfo
    {
        /// <summary>
        /// 数据库原生数据类型
        /// </summary>
        public string DbDataType { get; set; }
        /// <summary>
        /// 扩展属性
        /// </summary>
        public string PropertyText { get; set; }


    }
    public class CustormRazorTableInfo : RazorTableInfo
    {
        public List<CustormRazorColumnInfo> CustormColumns { get; set; }
    }

}`
